// Generated file

let allEmojis: [Emoji] = [
	Emoji(char: "#️⃣", names: ["hash", "hash-key"]),
	Emoji(char: "*️⃣", names: ["keycap-star", ""]),
	Emoji(char: "0️⃣", names: ["zero", "keycap-0"]),
	Emoji(char: "1️⃣", names: ["one", "keycap-1"]),
	Emoji(char: "2️⃣", names: ["two", "keycap-2"]),
	Emoji(char: "3️⃣", names: ["three", "keycap-3"]),
	Emoji(char: "4️⃣", names: ["four", "keycap-4"]),
	Emoji(char: "5️⃣", names: ["five", "keycap-5"]),
	Emoji(char: "6️⃣", names: ["six", "keycap-6"]),
	Emoji(char: "7️⃣", names: ["seven", "keycap-7"]),
	Emoji(char: "8️⃣", names: ["eight", "keycap-8"]),
	Emoji(char: "9️⃣", names: ["nine", "keycap-9"]),
	Emoji(char: "©️", names: ["copyright", "copyright-sign"]),
	Emoji(char: "®️", names: ["registered", "registered-sign"]),
	Emoji(char: "🀄", names: ["mahjong", "mahjong-tile-red-dragon"]),
	Emoji(char: "🃏", names: ["black-joker", "playing-card-black-joker"]),
	Emoji(char: "🅰️", names: ["a", "negative-squared-latin-capital-letter-a"]),
	Emoji(char: "🅱️", names: ["b", "negative-squared-latin-capital-letter-b"]),
	Emoji(char: "🅾️", names: ["o2", "negative-squared-latin-capital-letter-o"]),
	Emoji(char: "🅿️", names: ["parking", "negative-squared-latin-capital-letter-p"]),
	Emoji(char: "🆎", names: ["ab", "negative-squared-ab"]),
	Emoji(char: "🆑", names: ["cl", "squared-cl"]),
	Emoji(char: "🆒", names: ["cool", "squared-cool"]),
	Emoji(char: "🆓", names: ["free", "squared-free"]),
	Emoji(char: "🆔", names: ["id", "squared-id"]),
	Emoji(char: "🆕", names: ["new", "squared-new"]),
	Emoji(char: "🆖", names: ["ng", "squared-ng"]),
	Emoji(char: "🆗", names: ["ok", "squared-ok"]),
	Emoji(char: "🆘", names: ["sos", "squared-sos"]),
	Emoji(char: "🆙", names: ["up", "squared-up-with-exclamation-mark"]),
	Emoji(char: "🆚", names: ["vs", "squared-vs"]),
	Emoji(char: "🇦🇨", names: ["flag-ac", "regional-indicator-symbol-letters-ac"]),
	Emoji(char: "🇦🇩", names: ["flag-ad", "regional-indicator-symbol-letters-ad"]),
	Emoji(char: "🇦🇪", names: ["flag-ae", "regional-indicator-symbol-letters-ae"]),
	Emoji(char: "🇦🇫", names: ["flag-af", "regional-indicator-symbol-letters-af"]),
	Emoji(char: "🇦🇬", names: ["flag-ag", "regional-indicator-symbol-letters-ag"]),
	Emoji(char: "🇦🇮", names: ["flag-ai", "regional-indicator-symbol-letters-ai"]),
	Emoji(char: "🇦🇱", names: ["flag-al", "regional-indicator-symbol-letters-al"]),
	Emoji(char: "🇦🇲", names: ["flag-am", "regional-indicator-symbol-letters-am"]),
	Emoji(char: "🇦🇴", names: ["flag-ao", "regional-indicator-symbol-letters-ao"]),
	Emoji(char: "🇦🇶", names: ["flag-aq", "regional-indicator-symbol-letters-aq"]),
	Emoji(char: "🇦🇷", names: ["flag-ar", "regional-indicator-symbol-letters-ar"]),
	Emoji(char: "🇦🇸", names: ["flag-as", "regional-indicator-symbol-letters-as"]),
	Emoji(char: "🇦🇹", names: ["flag-at", "regional-indicator-symbol-letters-at"]),
	Emoji(char: "🇦🇺", names: ["flag-au", "regional-indicator-symbol-letters-au"]),
	Emoji(char: "🇦🇼", names: ["flag-aw", "regional-indicator-symbol-letters-aw"]),
	Emoji(char: "🇦🇽", names: ["flag-ax", "regional-indicator-symbol-letters-ax"]),
	Emoji(char: "🇦🇿", names: ["flag-az", "regional-indicator-symbol-letters-az"]),
	Emoji(char: "🇧🇦", names: ["flag-ba", "regional-indicator-symbol-letters-ba"]),
	Emoji(char: "🇧🇧", names: ["flag-bb", "regional-indicator-symbol-letters-bb"]),
	Emoji(char: "🇧🇩", names: ["flag-bd", "regional-indicator-symbol-letters-bd"]),
	Emoji(char: "🇧🇪", names: ["flag-be", "regional-indicator-symbol-letters-be"]),
	Emoji(char: "🇧🇫", names: ["flag-bf", "regional-indicator-symbol-letters-bf"]),
	Emoji(char: "🇧🇬", names: ["flag-bg", "regional-indicator-symbol-letters-bg"]),
	Emoji(char: "🇧🇭", names: ["flag-bh", "regional-indicator-symbol-letters-bh"]),
	Emoji(char: "🇧🇮", names: ["flag-bi", "regional-indicator-symbol-letters-bi"]),
	Emoji(char: "🇧🇯", names: ["flag-bj", "regional-indicator-symbol-letters-bj"]),
	Emoji(char: "🇧🇱", names: ["flag-bl", "regional-indicator-symbol-letters-bl"]),
	Emoji(char: "🇧🇲", names: ["flag-bm", "regional-indicator-symbol-letters-bm"]),
	Emoji(char: "🇧🇳", names: ["flag-bn", "regional-indicator-symbol-letters-bn"]),
	Emoji(char: "🇧🇴", names: ["flag-bo", "regional-indicator-symbol-letters-bo"]),
	Emoji(char: "🇧🇶", names: ["flag-bq", "regional-indicator-symbol-letters-bq"]),
	Emoji(char: "🇧🇷", names: ["flag-br", "regional-indicator-symbol-letters-br"]),
	Emoji(char: "🇧🇸", names: ["flag-bs", "regional-indicator-symbol-letters-bs"]),
	Emoji(char: "🇧🇹", names: ["flag-bt", "regional-indicator-symbol-letters-bt"]),
	Emoji(char: "🇧🇻", names: ["flag-bv", "regional-indicator-symbol-letters-bv"]),
	Emoji(char: "🇧🇼", names: ["flag-bw", "regional-indicator-symbol-letters-bw"]),
	Emoji(char: "🇧🇾", names: ["flag-by", "regional-indicator-symbol-letters-by"]),
	Emoji(char: "🇧🇿", names: ["flag-bz", "regional-indicator-symbol-letters-bz"]),
	Emoji(char: "🇨🇦", names: ["flag-ca", "regional-indicator-symbol-letters-ca"]),
	Emoji(char: "🇨🇨", names: ["flag-cc", "regional-indicator-symbol-letters-cc"]),
	Emoji(char: "🇨🇩", names: ["flag-cd", "regional-indicator-symbol-letters-cd"]),
	Emoji(char: "🇨🇫", names: ["flag-cf", "regional-indicator-symbol-letters-cf"]),
	Emoji(char: "🇨🇬", names: ["flag-cg", "regional-indicator-symbol-letters-cg"]),
	Emoji(char: "🇨🇭", names: ["flag-ch", "regional-indicator-symbol-letters-ch"]),
	Emoji(char: "🇨🇮", names: ["flag-ci", "regional-indicator-symbol-letters-ci"]),
	Emoji(char: "🇨🇰", names: ["flag-ck", "regional-indicator-symbol-letters-ck"]),
	Emoji(char: "🇨🇱", names: ["flag-cl", "regional-indicator-symbol-letters-cl"]),
	Emoji(char: "🇨🇲", names: ["flag-cm", "regional-indicator-symbol-letters-cm"]),
	Emoji(char: "🇨🇳", names: ["cn", "regional-indicator-symbol-letters-cn"]),
	Emoji(char: "🇨🇴", names: ["flag-co", "regional-indicator-symbol-letters-co"]),
	Emoji(char: "🇨🇵", names: ["flag-cp", "regional-indicator-symbol-letters-cp"]),
	Emoji(char: "🇨🇷", names: ["flag-cr", "regional-indicator-symbol-letters-cr"]),
	Emoji(char: "🇨🇺", names: ["flag-cu", "regional-indicator-symbol-letters-cu"]),
	Emoji(char: "🇨🇻", names: ["flag-cv", "regional-indicator-symbol-letters-cv"]),
	Emoji(char: "🇨🇼", names: ["flag-cw", "regional-indicator-symbol-letters-cw"]),
	Emoji(char: "🇨🇽", names: ["flag-cx", "regional-indicator-symbol-letters-cx"]),
	Emoji(char: "🇨🇾", names: ["flag-cy", "regional-indicator-symbol-letters-cy"]),
	Emoji(char: "🇨🇿", names: ["flag-cz", "regional-indicator-symbol-letters-cz"]),
	Emoji(char: "🇩🇪", names: ["de", "regional-indicator-symbol-letters-de"]),
	Emoji(char: "🇩🇬", names: ["flag-dg", "regional-indicator-symbol-letters-dg"]),
	Emoji(char: "🇩🇯", names: ["flag-dj", "regional-indicator-symbol-letters-dj"]),
	Emoji(char: "🇩🇰", names: ["flag-dk", "regional-indicator-symbol-letters-dk"]),
	Emoji(char: "🇩🇲", names: ["flag-dm", "regional-indicator-symbol-letters-dm"]),
	Emoji(char: "🇩🇴", names: ["flag-do", "regional-indicator-symbol-letters-do"]),
	Emoji(char: "🇩🇿", names: ["flag-dz", "regional-indicator-symbol-letters-dz"]),
	Emoji(char: "🇪🇦", names: ["flag-ea", "regional-indicator-symbol-letters-ea"]),
	Emoji(char: "🇪🇨", names: ["flag-ec", "regional-indicator-symbol-letters-ec"]),
	Emoji(char: "🇪🇪", names: ["flag-ee", "regional-indicator-symbol-letters-ee"]),
	Emoji(char: "🇪🇬", names: ["flag-eg", "regional-indicator-symbol-letters-eg"]),
	Emoji(char: "🇪🇭", names: ["flag-eh", "regional-indicator-symbol-letters-eh"]),
	Emoji(char: "🇪🇷", names: ["flag-er", "regional-indicator-symbol-letters-er"]),
	Emoji(char: "🇪🇸", names: ["es", "regional-indicator-symbol-letters-es"]),
	Emoji(char: "🇪🇹", names: ["flag-et", "regional-indicator-symbol-letters-et"]),
	Emoji(char: "🇪🇺", names: ["flag-eu", "regional-indicator-symbol-letters-eu"]),
	Emoji(char: "🇫🇮", names: ["flag-fi", "regional-indicator-symbol-letters-fi"]),
	Emoji(char: "🇫🇯", names: ["flag-fj", "regional-indicator-symbol-letters-fj"]),
	Emoji(char: "🇫🇰", names: ["flag-fk", "regional-indicator-symbol-letters-fk"]),
	Emoji(char: "🇫🇲", names: ["flag-fm", "regional-indicator-symbol-letters-fm"]),
	Emoji(char: "🇫🇴", names: ["flag-fo", "regional-indicator-symbol-letters-fo"]),
	Emoji(char: "🇫🇷", names: ["fr", "regional-indicator-symbol-letters-fr"]),
	Emoji(char: "🇬🇦", names: ["flag-ga", "regional-indicator-symbol-letters-ga"]),
	Emoji(char: "🇬🇧", names: ["gb", "regional-indicator-symbol-letters-gb"]),
	Emoji(char: "🇬🇩", names: ["flag-gd", "regional-indicator-symbol-letters-gd"]),
	Emoji(char: "🇬🇪", names: ["flag-ge", "regional-indicator-symbol-letters-ge"]),
	Emoji(char: "🇬🇫", names: ["flag-gf", "regional-indicator-symbol-letters-gf"]),
	Emoji(char: "🇬🇬", names: ["flag-gg", "regional-indicator-symbol-letters-gg"]),
	Emoji(char: "🇬🇭", names: ["flag-gh", "regional-indicator-symbol-letters-gh"]),
	Emoji(char: "🇬🇮", names: ["flag-gi", "regional-indicator-symbol-letters-gi"]),
	Emoji(char: "🇬🇱", names: ["flag-gl", "regional-indicator-symbol-letters-gl"]),
	Emoji(char: "🇬🇲", names: ["flag-gm", "regional-indicator-symbol-letters-gm"]),
	Emoji(char: "🇬🇳", names: ["flag-gn", "regional-indicator-symbol-letters-gn"]),
	Emoji(char: "🇬🇵", names: ["flag-gp", "regional-indicator-symbol-letters-gp"]),
	Emoji(char: "🇬🇶", names: ["flag-gq", "regional-indicator-symbol-letters-gq"]),
	Emoji(char: "🇬🇷", names: ["flag-gr", "regional-indicator-symbol-letters-gr"]),
	Emoji(char: "🇬🇸", names: ["flag-gs", "regional-indicator-symbol-letters-gs"]),
	Emoji(char: "🇬🇹", names: ["flag-gt", "regional-indicator-symbol-letters-gt"]),
	Emoji(char: "🇬🇺", names: ["flag-gu", "regional-indicator-symbol-letters-gu"]),
	Emoji(char: "🇬🇼", names: ["flag-gw", "regional-indicator-symbol-letters-gw"]),
	Emoji(char: "🇬🇾", names: ["flag-gy", "regional-indicator-symbol-letters-gy"]),
	Emoji(char: "🇭🇰", names: ["flag-hk", "regional-indicator-symbol-letters-hk"]),
	Emoji(char: "🇭🇲", names: ["flag-hm", "regional-indicator-symbol-letters-hm"]),
	Emoji(char: "🇭🇳", names: ["flag-hn", "regional-indicator-symbol-letters-hn"]),
	Emoji(char: "🇭🇷", names: ["flag-hr", "regional-indicator-symbol-letters-hr"]),
	Emoji(char: "🇭🇹", names: ["flag-ht", "regional-indicator-symbol-letters-ht"]),
	Emoji(char: "🇭🇺", names: ["flag-hu", "regional-indicator-symbol-letters-hu"]),
	Emoji(char: "🇮🇨", names: ["flag-ic", "regional-indicator-symbol-letters-ic"]),
	Emoji(char: "🇮🇩", names: ["flag-id", "regional-indicator-symbol-letters-id"]),
	Emoji(char: "🇮🇪", names: ["flag-ie", "regional-indicator-symbol-letters-ie"]),
	Emoji(char: "🇮🇱", names: ["flag-il", "regional-indicator-symbol-letters-il"]),
	Emoji(char: "🇮🇲", names: ["flag-im", "regional-indicator-symbol-letters-im"]),
	Emoji(char: "🇮🇳", names: ["flag-in", "regional-indicator-symbol-letters-in"]),
	Emoji(char: "🇮🇴", names: ["flag-io", "regional-indicator-symbol-letters-io"]),
	Emoji(char: "🇮🇶", names: ["flag-iq", "regional-indicator-symbol-letters-iq"]),
	Emoji(char: "🇮🇷", names: ["flag-ir", "regional-indicator-symbol-letters-ir"]),
	Emoji(char: "🇮🇸", names: ["flag-is", "regional-indicator-symbol-letters-is"]),
	Emoji(char: "🇮🇹", names: ["it", "regional-indicator-symbol-letters-it"]),
	Emoji(char: "🇯🇪", names: ["flag-je", "regional-indicator-symbol-letters-je"]),
	Emoji(char: "🇯🇲", names: ["flag-jm", "regional-indicator-symbol-letters-jm"]),
	Emoji(char: "🇯🇴", names: ["flag-jo", "regional-indicator-symbol-letters-jo"]),
	Emoji(char: "🇯🇵", names: ["jp", "regional-indicator-symbol-letters-jp"]),
	Emoji(char: "🇰🇪", names: ["flag-ke", "regional-indicator-symbol-letters-ke"]),
	Emoji(char: "🇰🇬", names: ["flag-kg", "regional-indicator-symbol-letters-kg"]),
	Emoji(char: "🇰🇭", names: ["flag-kh", "regional-indicator-symbol-letters-kh"]),
	Emoji(char: "🇰🇮", names: ["flag-ki", "regional-indicator-symbol-letters-ki"]),
	Emoji(char: "🇰🇲", names: ["flag-km", "regional-indicator-symbol-letters-km"]),
	Emoji(char: "🇰🇳", names: ["flag-kn", "regional-indicator-symbol-letters-kn"]),
	Emoji(char: "🇰🇵", names: ["flag-kp", "regional-indicator-symbol-letters-kp"]),
	Emoji(char: "🇰🇷", names: ["kr", "regional-indicator-symbol-letters-kr"]),
	Emoji(char: "🇰🇼", names: ["flag-kw", "regional-indicator-symbol-letters-kw"]),
	Emoji(char: "🇰🇾", names: ["flag-ky", "regional-indicator-symbol-letters-ky"]),
	Emoji(char: "🇰🇿", names: ["flag-kz", "regional-indicator-symbol-letters-kz"]),
	Emoji(char: "🇱🇦", names: ["flag-la", "regional-indicator-symbol-letters-la"]),
	Emoji(char: "🇱🇧", names: ["flag-lb", "regional-indicator-symbol-letters-lb"]),
	Emoji(char: "🇱🇨", names: ["flag-lc", "regional-indicator-symbol-letters-lc"]),
	Emoji(char: "🇱🇮", names: ["flag-li", "regional-indicator-symbol-letters-li"]),
	Emoji(char: "🇱🇰", names: ["flag-lk", "regional-indicator-symbol-letters-lk"]),
	Emoji(char: "🇱🇷", names: ["flag-lr", "regional-indicator-symbol-letters-lr"]),
	Emoji(char: "🇱🇸", names: ["flag-ls", "regional-indicator-symbol-letters-ls"]),
	Emoji(char: "🇱🇹", names: ["flag-lt", "regional-indicator-symbol-letters-lt"]),
	Emoji(char: "🇱🇺", names: ["flag-lu", "regional-indicator-symbol-letters-lu"]),
	Emoji(char: "🇱🇻", names: ["flag-lv", "regional-indicator-symbol-letters-lv"]),
	Emoji(char: "🇱🇾", names: ["flag-ly", "regional-indicator-symbol-letters-ly"]),
	Emoji(char: "🇲🇦", names: ["flag-ma", "regional-indicator-symbol-letters-ma"]),
	Emoji(char: "🇲🇨", names: ["flag-mc", "regional-indicator-symbol-letters-mc"]),
	Emoji(char: "🇲🇩", names: ["flag-md", "regional-indicator-symbol-letters-md"]),
	Emoji(char: "🇲🇪", names: ["flag-me", "regional-indicator-symbol-letters-me"]),
	Emoji(char: "🇲🇫", names: ["flag-mf", "regional-indicator-symbol-letters-mf"]),
	Emoji(char: "🇲🇬", names: ["flag-mg", "regional-indicator-symbol-letters-mg"]),
	Emoji(char: "🇲🇭", names: ["flag-mh", "regional-indicator-symbol-letters-mh"]),
	Emoji(char: "🇲🇰", names: ["flag-mk", "regional-indicator-symbol-letters-mk"]),
	Emoji(char: "🇲🇱", names: ["flag-ml", "regional-indicator-symbol-letters-ml"]),
	Emoji(char: "🇲🇲", names: ["flag-mm", "regional-indicator-symbol-letters-mm"]),
	Emoji(char: "🇲🇳", names: ["flag-mn", "regional-indicator-symbol-letters-mn"]),
	Emoji(char: "🇲🇴", names: ["flag-mo", "regional-indicator-symbol-letters-mo"]),
	Emoji(char: "🇲🇵", names: ["flag-mp", "regional-indicator-symbol-letters-mp"]),
	Emoji(char: "🇲🇶", names: ["flag-mq", "regional-indicator-symbol-letters-mq"]),
	Emoji(char: "🇲🇷", names: ["flag-mr", "regional-indicator-symbol-letters-mr"]),
	Emoji(char: "🇲🇸", names: ["flag-ms", "regional-indicator-symbol-letters-ms"]),
	Emoji(char: "🇲🇹", names: ["flag-mt", "regional-indicator-symbol-letters-mt"]),
	Emoji(char: "🇲🇺", names: ["flag-mu", "regional-indicator-symbol-letters-mu"]),
	Emoji(char: "🇲🇻", names: ["flag-mv", "regional-indicator-symbol-letters-mv"]),
	Emoji(char: "🇲🇼", names: ["flag-mw", "regional-indicator-symbol-letters-mw"]),
	Emoji(char: "🇲🇽", names: ["flag-mx", "regional-indicator-symbol-letters-mx"]),
	Emoji(char: "🇲🇾", names: ["flag-my", "regional-indicator-symbol-letters-my"]),
	Emoji(char: "🇲🇿", names: ["flag-mz", "regional-indicator-symbol-letters-mz"]),
	Emoji(char: "🇳🇦", names: ["flag-na", "regional-indicator-symbol-letters-na"]),
	Emoji(char: "🇳🇨", names: ["flag-nc", "regional-indicator-symbol-letters-nc"]),
	Emoji(char: "🇳🇪", names: ["flag-ne", "regional-indicator-symbol-letters-ne"]),
	Emoji(char: "🇳🇫", names: ["flag-nf", "regional-indicator-symbol-letters-nf"]),
	Emoji(char: "🇳🇬", names: ["flag-ng", "regional-indicator-symbol-letters-ng"]),
	Emoji(char: "🇳🇮", names: ["flag-ni", "regional-indicator-symbol-letters-ni"]),
	Emoji(char: "🇳🇱", names: ["flag-nl", "regional-indicator-symbol-letters-nl"]),
	Emoji(char: "🇳🇴", names: ["flag-no", "regional-indicator-symbol-letters-no"]),
	Emoji(char: "🇳🇵", names: ["flag-np", "regional-indicator-symbol-letters-np"]),
	Emoji(char: "🇳🇷", names: ["flag-nr", "regional-indicator-symbol-letters-nr"]),
	Emoji(char: "🇳🇺", names: ["flag-nu", "regional-indicator-symbol-letters-nu"]),
	Emoji(char: "🇳🇿", names: ["flag-nz", "regional-indicator-symbol-letters-nz"]),
	Emoji(char: "🇴🇲", names: ["flag-om", "regional-indicator-symbol-letters-om"]),
	Emoji(char: "🇵🇦", names: ["flag-pa", "regional-indicator-symbol-letters-pa"]),
	Emoji(char: "🇵🇪", names: ["flag-pe", "regional-indicator-symbol-letters-pe"]),
	Emoji(char: "🇵🇫", names: ["flag-pf", "regional-indicator-symbol-letters-pf"]),
	Emoji(char: "🇵🇬", names: ["flag-pg", "regional-indicator-symbol-letters-pg"]),
	Emoji(char: "🇵🇭", names: ["flag-ph", "regional-indicator-symbol-letters-ph"]),
	Emoji(char: "🇵🇰", names: ["flag-pk", "regional-indicator-symbol-letters-pk"]),
	Emoji(char: "🇵🇱", names: ["flag-pl", "regional-indicator-symbol-letters-pl"]),
	Emoji(char: "🇵🇲", names: ["flag-pm", "regional-indicator-symbol-letters-pm"]),
	Emoji(char: "🇵🇳", names: ["flag-pn", "regional-indicator-symbol-letters-pn"]),
	Emoji(char: "🇵🇷", names: ["flag-pr", "regional-indicator-symbol-letters-pr"]),
	Emoji(char: "🇵🇸", names: ["flag-ps", "regional-indicator-symbol-letters-ps"]),
	Emoji(char: "🇵🇹", names: ["flag-pt", "regional-indicator-symbol-letters-pt"]),
	Emoji(char: "🇵🇼", names: ["flag-pw", "regional-indicator-symbol-letters-pw"]),
	Emoji(char: "🇵🇾", names: ["flag-py", "regional-indicator-symbol-letters-py"]),
	Emoji(char: "🇶🇦", names: ["flag-qa", "regional-indicator-symbol-letters-qa"]),
	Emoji(char: "🇷🇪", names: ["flag-re", "regional-indicator-symbol-letters-re"]),
	Emoji(char: "🇷🇴", names: ["flag-ro", "regional-indicator-symbol-letters-ro"]),
	Emoji(char: "🇷🇸", names: ["flag-rs", "regional-indicator-symbol-letters-rs"]),
	Emoji(char: "🇷🇺", names: ["ru", "regional-indicator-symbol-letters-ru"]),
	Emoji(char: "🇷🇼", names: ["flag-rw", "regional-indicator-symbol-letters-rw"]),
	Emoji(char: "🇸🇦", names: ["flag-sa", "regional-indicator-symbol-letters-sa"]),
	Emoji(char: "🇸🇧", names: ["flag-sb", "regional-indicator-symbol-letters-sb"]),
	Emoji(char: "🇸🇨", names: ["flag-sc", "regional-indicator-symbol-letters-sc"]),
	Emoji(char: "🇸🇩", names: ["flag-sd", "regional-indicator-symbol-letters-sd"]),
	Emoji(char: "🇸🇪", names: ["flag-se", "regional-indicator-symbol-letters-se"]),
	Emoji(char: "🇸🇬", names: ["flag-sg", "regional-indicator-symbol-letters-sg"]),
	Emoji(char: "🇸🇭", names: ["flag-sh", "regional-indicator-symbol-letters-sh"]),
	Emoji(char: "🇸🇮", names: ["flag-si", "regional-indicator-symbol-letters-si"]),
	Emoji(char: "🇸🇯", names: ["flag-sj", "regional-indicator-symbol-letters-sj"]),
	Emoji(char: "🇸🇰", names: ["flag-sk", "regional-indicator-symbol-letters-sk"]),
	Emoji(char: "🇸🇱", names: ["flag-sl", "regional-indicator-symbol-letters-sl"]),
	Emoji(char: "🇸🇲", names: ["flag-sm", "regional-indicator-symbol-letters-sm"]),
	Emoji(char: "🇸🇳", names: ["flag-sn", "regional-indicator-symbol-letters-sn"]),
	Emoji(char: "🇸🇴", names: ["flag-so", "regional-indicator-symbol-letters-so"]),
	Emoji(char: "🇸🇷", names: ["flag-sr", "regional-indicator-symbol-letters-sr"]),
	Emoji(char: "🇸🇸", names: ["flag-ss", "regional-indicator-symbol-letters-ss"]),
	Emoji(char: "🇸🇹", names: ["flag-st", "regional-indicator-symbol-letters-st"]),
	Emoji(char: "🇸🇻", names: ["flag-sv", "regional-indicator-symbol-letters-sv"]),
	Emoji(char: "🇸🇽", names: ["flag-sx", "regional-indicator-symbol-letters-sx"]),
	Emoji(char: "🇸🇾", names: ["flag-sy", "regional-indicator-symbol-letters-sy"]),
	Emoji(char: "🇸🇿", names: ["flag-sz", "regional-indicator-symbol-letters-sz"]),
	Emoji(char: "🇹🇦", names: ["flag-ta", "regional-indicator-symbol-letters-ta"]),
	Emoji(char: "🇹🇨", names: ["flag-tc", "regional-indicator-symbol-letters-tc"]),
	Emoji(char: "🇹🇩", names: ["flag-td", "regional-indicator-symbol-letters-td"]),
	Emoji(char: "🇹🇫", names: ["flag-tf", "regional-indicator-symbol-letters-tf"]),
	Emoji(char: "🇹🇬", names: ["flag-tg", "regional-indicator-symbol-letters-tg"]),
	Emoji(char: "🇹🇭", names: ["flag-th", "regional-indicator-symbol-letters-th"]),
	Emoji(char: "🇹🇯", names: ["flag-tj", "regional-indicator-symbol-letters-tj"]),
	Emoji(char: "🇹🇰", names: ["flag-tk", "regional-indicator-symbol-letters-tk"]),
	Emoji(char: "🇹🇱", names: ["flag-tl", "regional-indicator-symbol-letters-tl"]),
	Emoji(char: "🇹🇲", names: ["flag-tm", "regional-indicator-symbol-letters-tm"]),
	Emoji(char: "🇹🇳", names: ["flag-tn", "regional-indicator-symbol-letters-tn"]),
	Emoji(char: "🇹🇴", names: ["flag-to", "regional-indicator-symbol-letters-to"]),
	Emoji(char: "🇹🇷", names: ["flag-tr", "regional-indicator-symbol-letters-tr"]),
	Emoji(char: "🇹🇹", names: ["flag-tt", "regional-indicator-symbol-letters-tt"]),
	Emoji(char: "🇹🇻", names: ["flag-tv", "regional-indicator-symbol-letters-tv"]),
	Emoji(char: "🇹🇼", names: ["flag-tw", "regional-indicator-symbol-letters-tw"]),
	Emoji(char: "🇹🇿", names: ["flag-tz", "regional-indicator-symbol-letters-tz"]),
	Emoji(char: "🇺🇦", names: ["flag-ua", "regional-indicator-symbol-letters-ua"]),
	Emoji(char: "🇺🇬", names: ["flag-ug", "regional-indicator-symbol-letters-ug"]),
	Emoji(char: "🇺🇲", names: ["flag-um", "regional-indicator-symbol-letters-um"]),
	Emoji(char: "🇺🇳", names: ["flag-un", "regional-indicator-symbol-letters-un"]),
	Emoji(char: "🇺🇸", names: ["us", "regional-indicator-symbol-letters-us"]),
	Emoji(char: "🇺🇾", names: ["flag-uy", "regional-indicator-symbol-letters-uy"]),
	Emoji(char: "🇺🇿", names: ["flag-uz", "regional-indicator-symbol-letters-uz"]),
	Emoji(char: "🇻🇦", names: ["flag-va", "regional-indicator-symbol-letters-va"]),
	Emoji(char: "🇻🇨", names: ["flag-vc", "regional-indicator-symbol-letters-vc"]),
	Emoji(char: "🇻🇪", names: ["flag-ve", "regional-indicator-symbol-letters-ve"]),
	Emoji(char: "🇻🇬", names: ["flag-vg", "regional-indicator-symbol-letters-vg"]),
	Emoji(char: "🇻🇮", names: ["flag-vi", "regional-indicator-symbol-letters-vi"]),
	Emoji(char: "🇻🇳", names: ["flag-vn", "regional-indicator-symbol-letters-vn"]),
	Emoji(char: "🇻🇺", names: ["flag-vu", "regional-indicator-symbol-letters-vu"]),
	Emoji(char: "🇼🇫", names: ["flag-wf", "regional-indicator-symbol-letters-wf"]),
	Emoji(char: "🇼🇸", names: ["flag-ws", "regional-indicator-symbol-letters-ws"]),
	Emoji(char: "🇽🇰", names: ["flag-xk", "regional-indicator-symbol-letters-xk"]),
	Emoji(char: "🇾🇪", names: ["flag-ye", "regional-indicator-symbol-letters-ye"]),
	Emoji(char: "🇾🇹", names: ["flag-yt", "regional-indicator-symbol-letters-yt"]),
	Emoji(char: "🇿🇦", names: ["flag-za", "regional-indicator-symbol-letters-za"]),
	Emoji(char: "🇿🇲", names: ["flag-zm", "regional-indicator-symbol-letters-zm"]),
	Emoji(char: "🇿🇼", names: ["flag-zw", "regional-indicator-symbol-letters-zw"]),
	Emoji(char: "🈁", names: ["koko", "squared-katakana-koko"]),
	Emoji(char: "🈂️", names: ["sa", "squared-katakana-sa"]),
	Emoji(char: "🈚", names: ["u7121", "squared-cjk-unified-ideograph-7121"]),
	Emoji(char: "🈯", names: ["u6307", "squared-cjk-unified-ideograph-6307"]),
	Emoji(char: "🈲", names: ["u7981", "squared-cjk-unified-ideograph-7981"]),
	Emoji(char: "🈳", names: ["u7a7a", "squared-cjk-unified-ideograph-7a7a"]),
	Emoji(char: "🈴", names: ["u5408", "squared-cjk-unified-ideograph-5408"]),
	Emoji(char: "🈵", names: ["u6e80", "squared-cjk-unified-ideograph-6e80"]),
	Emoji(char: "🈶", names: ["u6709", "squared-cjk-unified-ideograph-6709"]),
	Emoji(char: "🈷️", names: ["u6708", "squared-cjk-unified-ideograph-6708"]),
	Emoji(char: "🈸", names: ["u7533", "squared-cjk-unified-ideograph-7533"]),
	Emoji(char: "🈹", names: ["u5272", "squared-cjk-unified-ideograph-5272"]),
	Emoji(char: "🈺", names: ["u55b6", "squared-cjk-unified-ideograph-55b6"]),
	Emoji(char: "🉐", names: ["ideograph-advantage", "circled-ideograph-advantage"]),
	Emoji(char: "🉑", names: ["accept", "circled-ideograph-accept"]),
	Emoji(char: "🌀", names: ["cyclone"]),
	Emoji(char: "🌁", names: ["foggy"]),
	Emoji(char: "🌂", names: ["closed-umbrella"]),
	Emoji(char: "🌃", names: ["night-with-stars"]),
	Emoji(char: "🌄", names: ["sunrise-over-mountains"]),
	Emoji(char: "🌅", names: ["sunrise"]),
	Emoji(char: "🌆", names: ["city-sunset", "cityscape-at-dusk"]),
	Emoji(char: "🌇", names: ["city-sunrise", "sunset-over-buildings"]),
	Emoji(char: "🌈", names: ["rainbow"]),
	Emoji(char: "🌉", names: ["bridge-at-night"]),
	Emoji(char: "🌊", names: ["ocean", "water-wave"]),
	Emoji(char: "🌋", names: ["volcano"]),
	Emoji(char: "🌌", names: ["milky-way"]),
	Emoji(char: "🌍", names: ["earth-africa", "earth-globe-europe-africa"]),
	Emoji(char: "🌎", names: ["earth-americas", "earth-globe-americas"]),
	Emoji(char: "🌏", names: ["earth-asia", "earth-globe-asia-australia"]),
	Emoji(char: "🌐", names: ["globe-with-meridians"]),
	Emoji(char: "🌑", names: ["new-moon", "new-moon-symbol"]),
	Emoji(char: "🌒", names: ["waxing-crescent-moon", "waxing-crescent-moon-symbol"]),
	Emoji(char: "🌓", names: ["first-quarter-moon", "first-quarter-moon-symbol"]),
	Emoji(char: "🌔", names: ["moon", "waxing-gibbous-moon-symbol"]),
	Emoji(char: "🌕", names: ["full-moon", "full-moon-symbol"]),
	Emoji(char: "🌖", names: ["waning-gibbous-moon", "waning-gibbous-moon-symbol"]),
	Emoji(char: "🌗", names: ["last-quarter-moon", "last-quarter-moon-symbol"]),
	Emoji(char: "🌘", names: ["waning-crescent-moon", "waning-crescent-moon-symbol"]),
	Emoji(char: "🌙", names: ["crescent-moon"]),
	Emoji(char: "🌚", names: ["new-moon-with-face"]),
	Emoji(char: "🌛", names: ["first-quarter-moon-with-face"]),
	Emoji(char: "🌜", names: ["last-quarter-moon-with-face"]),
	Emoji(char: "🌝", names: ["full-moon-with-face"]),
	Emoji(char: "🌞", names: ["sun-with-face"]),
	Emoji(char: "🌟", names: ["star2", "glowing-star"]),
	Emoji(char: "🌠", names: ["stars", "shooting-star"]),
	Emoji(char: "🌡️", names: ["thermometer", ""]),
	Emoji(char: "🌤️", names: ["mostly-sunny", ""]),
	Emoji(char: "🌥️", names: ["barely-sunny", ""]),
	Emoji(char: "🌦️", names: ["partly-sunny-rain", ""]),
	Emoji(char: "🌧️", names: ["rain-cloud", ""]),
	Emoji(char: "🌨️", names: ["snow-cloud", ""]),
	Emoji(char: "🌩️", names: ["lightning", ""]),
	Emoji(char: "🌪️", names: ["tornado", ""]),
	Emoji(char: "🌫️", names: ["fog", ""]),
	Emoji(char: "🌬️", names: ["wind-blowing-face", ""]),
	Emoji(char: "🌭", names: ["hotdog", "hot-dog"]),
	Emoji(char: "🌮", names: ["taco"]),
	Emoji(char: "🌯", names: ["burrito"]),
	Emoji(char: "🌰", names: ["chestnut"]),
	Emoji(char: "🌱", names: ["seedling"]),
	Emoji(char: "🌲", names: ["evergreen-tree"]),
	Emoji(char: "🌳", names: ["deciduous-tree"]),
	Emoji(char: "🌴", names: ["palm-tree"]),
	Emoji(char: "🌵", names: ["cactus"]),
	Emoji(char: "🌶️", names: ["hot-pepper", ""]),
	Emoji(char: "🌷", names: ["tulip"]),
	Emoji(char: "🌸", names: ["cherry-blossom"]),
	Emoji(char: "🌹", names: ["rose"]),
	Emoji(char: "🌺", names: ["hibiscus"]),
	Emoji(char: "🌻", names: ["sunflower"]),
	Emoji(char: "🌼", names: ["blossom"]),
	Emoji(char: "🌽", names: ["corn", "ear-of-maize"]),
	Emoji(char: "🌾", names: ["ear-of-rice"]),
	Emoji(char: "🌿", names: ["herb"]),
	Emoji(char: "🍀", names: ["four-leaf-clover"]),
	Emoji(char: "🍁", names: ["maple-leaf"]),
	Emoji(char: "🍂", names: ["fallen-leaf"]),
	Emoji(char: "🍃", names: ["leaves", "leaf-fluttering-in-wind"]),
	Emoji(char: "🍄", names: ["mushroom"]),
	Emoji(char: "🍅", names: ["tomato"]),
	Emoji(char: "🍆", names: ["eggplant", "aubergine"]),
	Emoji(char: "🍇", names: ["grapes"]),
	Emoji(char: "🍈", names: ["melon"]),
	Emoji(char: "🍉", names: ["watermelon"]),
	Emoji(char: "🍊", names: ["tangerine"]),
	Emoji(char: "🍋", names: ["lemon"]),
	Emoji(char: "🍌", names: ["banana"]),
	Emoji(char: "🍍", names: ["pineapple"]),
	Emoji(char: "🍎", names: ["apple", "red-apple"]),
	Emoji(char: "🍏", names: ["green-apple"]),
	Emoji(char: "🍐", names: ["pear"]),
	Emoji(char: "🍑", names: ["peach"]),
	Emoji(char: "🍒", names: ["cherries"]),
	Emoji(char: "🍓", names: ["strawberry"]),
	Emoji(char: "🍔", names: ["hamburger"]),
	Emoji(char: "🍕", names: ["pizza", "slice-of-pizza"]),
	Emoji(char: "🍖", names: ["meat-on-bone"]),
	Emoji(char: "🍗", names: ["poultry-leg"]),
	Emoji(char: "🍘", names: ["rice-cracker"]),
	Emoji(char: "🍙", names: ["rice-ball"]),
	Emoji(char: "🍚", names: ["rice", "cooked-rice"]),
	Emoji(char: "🍛", names: ["curry", "curry-and-rice"]),
	Emoji(char: "🍜", names: ["ramen", "steaming-bowl"]),
	Emoji(char: "🍝", names: ["spaghetti"]),
	Emoji(char: "🍞", names: ["bread"]),
	Emoji(char: "🍟", names: ["fries", "french-fries"]),
	Emoji(char: "🍠", names: ["sweet-potato", "roasted-sweet-potato"]),
	Emoji(char: "🍡", names: ["dango"]),
	Emoji(char: "🍢", names: ["oden"]),
	Emoji(char: "🍣", names: ["sushi"]),
	Emoji(char: "🍤", names: ["fried-shrimp"]),
	Emoji(char: "🍥", names: ["fish-cake", "fish-cake-with-swirl-design"]),
	Emoji(char: "🍦", names: ["icecream", "soft-ice-cream"]),
	Emoji(char: "🍧", names: ["shaved-ice"]),
	Emoji(char: "🍨", names: ["ice-cream"]),
	Emoji(char: "🍩", names: ["doughnut"]),
	Emoji(char: "🍪", names: ["cookie"]),
	Emoji(char: "🍫", names: ["chocolate-bar"]),
	Emoji(char: "🍬", names: ["candy"]),
	Emoji(char: "🍭", names: ["lollipop"]),
	Emoji(char: "🍮", names: ["custard"]),
	Emoji(char: "🍯", names: ["honey-pot"]),
	Emoji(char: "🍰", names: ["cake", "shortcake"]),
	Emoji(char: "🍱", names: ["bento", "bento-box"]),
	Emoji(char: "🍲", names: ["stew", "pot-of-food"]),
	Emoji(char: "🍳", names: ["fried-egg", "cooking"]),
	Emoji(char: "🍴", names: ["fork-and-knife"]),
	Emoji(char: "🍵", names: ["tea", "teacup-without-handle"]),
	Emoji(char: "🍶", names: ["sake", "sake-bottle-and-cup"]),
	Emoji(char: "🍷", names: ["wine-glass"]),
	Emoji(char: "🍸", names: ["cocktail", "cocktail-glass"]),
	Emoji(char: "🍹", names: ["tropical-drink"]),
	Emoji(char: "🍺", names: ["beer", "beer-mug"]),
	Emoji(char: "🍻", names: ["beers", "clinking-beer-mugs"]),
	Emoji(char: "🍼", names: ["baby-bottle"]),
	Emoji(char: "🍽️", names: ["knife-fork-plate", ""]),
	Emoji(char: "🍾", names: ["champagne", "bottle-with-popping-cork"]),
	Emoji(char: "🍿", names: ["popcorn"]),
	Emoji(char: "🎀", names: ["ribbon"]),
	Emoji(char: "🎁", names: ["gift", "wrapped-present"]),
	Emoji(char: "🎂", names: ["birthday", "birthday-cake"]),
	Emoji(char: "🎃", names: ["jack-o-lantern"]),
	Emoji(char: "🎄", names: ["christmas-tree"]),
	Emoji(char: "🎅", names: ["santa", "father-christmas"]),
	Emoji(char: "🎆", names: ["fireworks"]),
	Emoji(char: "🎇", names: ["sparkler", "firework-sparkler"]),
	Emoji(char: "🎈", names: ["balloon"]),
	Emoji(char: "🎉", names: ["tada", "party-popper"]),
	Emoji(char: "🎊", names: ["confetti-ball"]),
	Emoji(char: "🎋", names: ["tanabata-tree"]),
	Emoji(char: "🎌", names: ["crossed-flags"]),
	Emoji(char: "🎍", names: ["bamboo", "pine-decoration"]),
	Emoji(char: "🎎", names: ["dolls", "japanese-dolls"]),
	Emoji(char: "🎏", names: ["flags", "carp-streamer"]),
	Emoji(char: "🎐", names: ["wind-chime"]),
	Emoji(char: "🎑", names: ["rice-scene", "moon-viewing-ceremony"]),
	Emoji(char: "🎒", names: ["school-satchel"]),
	Emoji(char: "🎓", names: ["mortar-board", "graduation-cap"]),
	Emoji(char: "🎖️", names: ["medal", ""]),
	Emoji(char: "🎗️", names: ["reminder-ribbon", ""]),
	Emoji(char: "🎙️", names: ["studio-microphone", ""]),
	Emoji(char: "🎚️", names: ["level-slider", ""]),
	Emoji(char: "🎛️", names: ["control-knobs", ""]),
	Emoji(char: "🎞️", names: ["film-frames", ""]),
	Emoji(char: "🎟️", names: ["admission-tickets", ""]),
	Emoji(char: "🎠", names: ["carousel-horse"]),
	Emoji(char: "🎡", names: ["ferris-wheel"]),
	Emoji(char: "🎢", names: ["roller-coaster"]),
	Emoji(char: "🎣", names: ["fishing-pole-and-fish"]),
	Emoji(char: "🎤", names: ["microphone"]),
	Emoji(char: "🎥", names: ["movie-camera"]),
	Emoji(char: "🎦", names: ["cinema"]),
	Emoji(char: "🎧", names: ["headphones", "headphone"]),
	Emoji(char: "🎨", names: ["art", "artist-palette"]),
	Emoji(char: "🎩", names: ["tophat", "top-hat"]),
	Emoji(char: "🎪", names: ["circus-tent"]),
	Emoji(char: "🎫", names: ["ticket"]),
	Emoji(char: "🎬", names: ["clapper", "clapper-board"]),
	Emoji(char: "🎭", names: ["performing-arts"]),
	Emoji(char: "🎮", names: ["video-game"]),
	Emoji(char: "🎯", names: ["dart", "direct-hit"]),
	Emoji(char: "🎰", names: ["slot-machine"]),
	Emoji(char: "🎱", names: ["8ball", "billiards"]),
	Emoji(char: "🎲", names: ["game-die"]),
	Emoji(char: "🎳", names: ["bowling"]),
	Emoji(char: "🎴", names: ["flower-playing-cards"]),
	Emoji(char: "🎵", names: ["musical-note"]),
	Emoji(char: "🎶", names: ["notes", "multiple-musical-notes"]),
	Emoji(char: "🎷", names: ["saxophone"]),
	Emoji(char: "🎸", names: ["guitar"]),
	Emoji(char: "🎹", names: ["musical-keyboard"]),
	Emoji(char: "🎺", names: ["trumpet"]),
	Emoji(char: "🎻", names: ["violin"]),
	Emoji(char: "🎼", names: ["musical-score"]),
	Emoji(char: "🎽", names: ["running-shirt-with-sash"]),
	Emoji(char: "🎾", names: ["tennis", "tennis-racquet-and-ball"]),
	Emoji(char: "🎿", names: ["ski", "ski-and-ski-boot"]),
	Emoji(char: "🏀", names: ["basketball", "basketball-and-hoop"]),
	Emoji(char: "🏁", names: ["checkered-flag", "chequered-flag"]),
	Emoji(char: "🏂", names: ["snowboarder"]),
	Emoji(char: "🏃‍♀️", names: ["woman-running", ""]),
	Emoji(char: "🏃‍♂️", names: ["man-running", ""]),
	Emoji(char: "🏃", names: ["runner"]),
	Emoji(char: "🏄‍♀️", names: ["woman-surfing", ""]),
	Emoji(char: "🏄‍♂️", names: ["man-surfing", ""]),
	Emoji(char: "🏄", names: ["surfer"]),
	Emoji(char: "🏅", names: ["sports-medal"]),
	Emoji(char: "🏆", names: ["trophy"]),
	Emoji(char: "🏇", names: ["horse-racing"]),
	Emoji(char: "🏈", names: ["football", "american-football"]),
	Emoji(char: "🏉", names: ["rugby-football"]),
	Emoji(char: "🏊‍♀️", names: ["woman-swimming", ""]),
	Emoji(char: "🏊‍♂️", names: ["man-swimming", ""]),
	Emoji(char: "🏊", names: ["swimmer"]),
	Emoji(char: "🏋️‍♀️", names: ["woman-lifting-weights", ""]),
	Emoji(char: "🏋️‍♂️", names: ["man-lifting-weights", ""]),
	Emoji(char: "🏋️", names: ["weight-lifter", ""]),
	Emoji(char: "🏌️‍♀️", names: ["woman-golfing", ""]),
	Emoji(char: "🏌️‍♂️", names: ["man-golfing", ""]),
	Emoji(char: "🏌️", names: ["golfer", ""]),
	Emoji(char: "🏍️", names: ["racing-motorcycle", ""]),
	Emoji(char: "🏎️", names: ["racing-car", ""]),
	Emoji(char: "🏏", names: ["cricket-bat-and-ball"]),
	Emoji(char: "🏐", names: ["volleyball"]),
	Emoji(char: "🏑", names: ["field-hockey-stick-and-ball"]),
	Emoji(char: "🏒", names: ["ice-hockey-stick-and-puck"]),
	Emoji(char: "🏓", names: ["table-tennis-paddle-and-ball"]),
	Emoji(char: "🏔️", names: ["snow-capped-mountain", ""]),
	Emoji(char: "🏕️", names: ["camping", ""]),
	Emoji(char: "🏖️", names: ["beach-with-umbrella", ""]),
	Emoji(char: "🏗️", names: ["building-construction", ""]),
	Emoji(char: "🏘️", names: ["house-buildings", ""]),
	Emoji(char: "🏙️", names: ["cityscape", ""]),
	Emoji(char: "🏚️", names: ["derelict-house-building", ""]),
	Emoji(char: "🏛️", names: ["classical-building", ""]),
	Emoji(char: "🏜️", names: ["desert", ""]),
	Emoji(char: "🏝️", names: ["desert-island", ""]),
	Emoji(char: "🏞️", names: ["national-park", ""]),
	Emoji(char: "🏟️", names: ["stadium", ""]),
	Emoji(char: "🏠", names: ["house", "house-building"]),
	Emoji(char: "🏡", names: ["house-with-garden"]),
	Emoji(char: "🏢", names: ["office", "office-building"]),
	Emoji(char: "🏣", names: ["post-office", "japanese-post-office"]),
	Emoji(char: "🏤", names: ["european-post-office"]),
	Emoji(char: "🏥", names: ["hospital"]),
	Emoji(char: "🏦", names: ["bank"]),
	Emoji(char: "🏧", names: ["atm", "automated-teller-machine"]),
	Emoji(char: "🏨", names: ["hotel"]),
	Emoji(char: "🏩", names: ["love-hotel"]),
	Emoji(char: "🏪", names: ["convenience-store"]),
	Emoji(char: "🏫", names: ["school"]),
	Emoji(char: "🏬", names: ["department-store"]),
	Emoji(char: "🏭", names: ["factory"]),
	Emoji(char: "🏮", names: ["izakaya-lantern"]),
	Emoji(char: "🏯", names: ["japanese-castle"]),
	Emoji(char: "🏰", names: ["european-castle"]),
	Emoji(char: "🏳️‍🌈", names: ["rainbow-flag", ""]),
	Emoji(char: "🏳️", names: ["waving-white-flag", ""]),
	Emoji(char: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", names: ["flag-england", "regional-indicator-symbol-letters-england"]),
	Emoji(char: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", names: ["flag-scotland", "regional-indicator-symbol-letters-scotland"]),
	Emoji(char: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", names: ["flag-wales", "regional-indicator-symbol-letters-wales"]),
	Emoji(char: "🏴", names: ["waving-black-flag"]),
	Emoji(char: "🏵️", names: ["rosette", ""]),
	Emoji(char: "🏷️", names: ["label", ""]),
	Emoji(char: "🏸", names: ["badminton-racquet-and-shuttlecock"]),
	Emoji(char: "🏹", names: ["bow-and-arrow"]),
	Emoji(char: "🏺", names: ["amphora"]),
	Emoji(char: "🏻", names: ["skin-tone-2", "emoji-modifier-fitzpatrick-type-1-2"]),
	Emoji(char: "🏼", names: ["skin-tone-3", "emoji-modifier-fitzpatrick-type-3"]),
	Emoji(char: "🏽", names: ["skin-tone-4", "emoji-modifier-fitzpatrick-type-4"]),
	Emoji(char: "🏾", names: ["skin-tone-5", "emoji-modifier-fitzpatrick-type-5"]),
	Emoji(char: "🏿", names: ["skin-tone-6", "emoji-modifier-fitzpatrick-type-6"]),
	Emoji(char: "🐀", names: ["rat"]),
	Emoji(char: "🐁", names: ["mouse2", "mouse"]),
	Emoji(char: "🐂", names: ["ox"]),
	Emoji(char: "🐃", names: ["water-buffalo"]),
	Emoji(char: "🐄", names: ["cow2", "cow"]),
	Emoji(char: "🐅", names: ["tiger2", "tiger"]),
	Emoji(char: "🐆", names: ["leopard"]),
	Emoji(char: "🐇", names: ["rabbit2", "rabbit"]),
	Emoji(char: "🐈", names: ["cat2", "cat"]),
	Emoji(char: "🐉", names: ["dragon"]),
	Emoji(char: "🐊", names: ["crocodile"]),
	Emoji(char: "🐋", names: ["whale2", "whale"]),
	Emoji(char: "🐌", names: ["snail"]),
	Emoji(char: "🐍", names: ["snake"]),
	Emoji(char: "🐎", names: ["racehorse", "horse"]),
	Emoji(char: "🐏", names: ["ram"]),
	Emoji(char: "🐐", names: ["goat"]),
	Emoji(char: "🐑", names: ["sheep"]),
	Emoji(char: "🐒", names: ["monkey"]),
	Emoji(char: "🐓", names: ["rooster"]),
	Emoji(char: "🐔", names: ["chicken"]),
	Emoji(char: "🐕", names: ["dog2", "dog"]),
	Emoji(char: "🐖", names: ["pig2", "pig"]),
	Emoji(char: "🐗", names: ["boar"]),
	Emoji(char: "🐘", names: ["elephant"]),
	Emoji(char: "🐙", names: ["octopus"]),
	Emoji(char: "🐚", names: ["shell", "spiral-shell"]),
	Emoji(char: "🐛", names: ["bug"]),
	Emoji(char: "🐜", names: ["ant"]),
	Emoji(char: "🐝", names: ["bee", "honeybee"]),
	Emoji(char: "🐞", names: ["beetle", "lady-beetle"]),
	Emoji(char: "🐟", names: ["fish"]),
	Emoji(char: "🐠", names: ["tropical-fish"]),
	Emoji(char: "🐡", names: ["blowfish"]),
	Emoji(char: "🐢", names: ["turtle"]),
	Emoji(char: "🐣", names: ["hatching-chick"]),
	Emoji(char: "🐤", names: ["baby-chick"]),
	Emoji(char: "🐥", names: ["hatched-chick", "front-facing-baby-chick"]),
	Emoji(char: "🐦", names: ["bird"]),
	Emoji(char: "🐧", names: ["penguin"]),
	Emoji(char: "🐨", names: ["koala"]),
	Emoji(char: "🐩", names: ["poodle"]),
	Emoji(char: "🐪", names: ["dromedary-camel"]),
	Emoji(char: "🐫", names: ["camel", "bactrian-camel"]),
	Emoji(char: "🐬", names: ["dolphin"]),
	Emoji(char: "🐭", names: ["mouse", "mouse-face"]),
	Emoji(char: "🐮", names: ["cow", "cow-face"]),
	Emoji(char: "🐯", names: ["tiger", "tiger-face"]),
	Emoji(char: "🐰", names: ["rabbit", "rabbit-face"]),
	Emoji(char: "🐱", names: ["cat", "cat-face"]),
	Emoji(char: "🐲", names: ["dragon-face"]),
	Emoji(char: "🐳", names: ["whale", "spouting-whale"]),
	Emoji(char: "🐴", names: ["horse", "horse-face"]),
	Emoji(char: "🐵", names: ["monkey-face"]),
	Emoji(char: "🐶", names: ["dog", "dog-face"]),
	Emoji(char: "🐷", names: ["pig", "pig-face"]),
	Emoji(char: "🐸", names: ["frog", "frog-face"]),
	Emoji(char: "🐹", names: ["hamster", "hamster-face"]),
	Emoji(char: "🐺", names: ["wolf", "wolf-face"]),
	Emoji(char: "🐻", names: ["bear", "bear-face"]),
	Emoji(char: "🐼", names: ["panda-face"]),
	Emoji(char: "🐽", names: ["pig-nose"]),
	Emoji(char: "🐾", names: ["feet", "paw-prints"]),
	Emoji(char: "🐿️", names: ["chipmunk", ""]),
	Emoji(char: "👀", names: ["eyes"]),
	Emoji(char: "👁️‍🗨️", names: ["eye-in-speech-bubble", ""]),
	Emoji(char: "👁️", names: ["eye", ""]),
	Emoji(char: "👂", names: ["ear"]),
	Emoji(char: "👃", names: ["nose"]),
	Emoji(char: "👄", names: ["lips", "mouth"]),
	Emoji(char: "👅", names: ["tongue"]),
	Emoji(char: "👆", names: ["point-up-2", "white-up-pointing-backhand-index"]),
	Emoji(char: "👇", names: ["point-down", "white-down-pointing-backhand-index"]),
	Emoji(char: "👈", names: ["point-left", "white-left-pointing-backhand-index"]),
	Emoji(char: "👉", names: ["point-right", "white-right-pointing-backhand-index"]),
	Emoji(char: "👊", names: ["facepunch", "fisted-hand-sign"]),
	Emoji(char: "👋", names: ["wave", "waving-hand-sign"]),
	Emoji(char: "👌", names: ["ok-hand", "ok-hand-sign"]),
	Emoji(char: "👍", names: ["+1", "thumbs-up-sign"]),
	Emoji(char: "👎", names: ["-1", "thumbs-down-sign"]),
	Emoji(char: "👏", names: ["clap", "clapping-hands-sign"]),
	Emoji(char: "👐", names: ["open-hands", "open-hands-sign"]),
	Emoji(char: "👑", names: ["crown"]),
	Emoji(char: "👒", names: ["womans-hat"]),
	Emoji(char: "👓", names: ["eyeglasses"]),
	Emoji(char: "👔", names: ["necktie"]),
	Emoji(char: "👕", names: ["shirt", "t-shirt"]),
	Emoji(char: "👖", names: ["jeans"]),
	Emoji(char: "👗", names: ["dress"]),
	Emoji(char: "👘", names: ["kimono"]),
	Emoji(char: "👙", names: ["bikini"]),
	Emoji(char: "👚", names: ["womans-clothes"]),
	Emoji(char: "👛", names: ["purse"]),
	Emoji(char: "👜", names: ["handbag"]),
	Emoji(char: "👝", names: ["pouch"]),
	Emoji(char: "👞", names: ["mans-shoe"]),
	Emoji(char: "👟", names: ["athletic-shoe"]),
	Emoji(char: "👠", names: ["high-heel", "high-heeled-shoe"]),
	Emoji(char: "👡", names: ["sandal", "womans-sandal"]),
	Emoji(char: "👢", names: ["boot", "womans-boots"]),
	Emoji(char: "👣", names: ["footprints"]),
	Emoji(char: "👤", names: ["bust-in-silhouette"]),
	Emoji(char: "👥", names: ["busts-in-silhouette"]),
	Emoji(char: "👦", names: ["boy"]),
	Emoji(char: "👧", names: ["girl"]),
	Emoji(char: "👨‍🌾", names: ["male-farmer", ""]),
	Emoji(char: "👨‍🍳", names: ["male-cook", ""]),
	Emoji(char: "👨‍🎓", names: ["male-student", ""]),
	Emoji(char: "👨‍🎤", names: ["male-singer", ""]),
	Emoji(char: "👨‍🎨", names: ["male-artist", ""]),
	Emoji(char: "👨‍🏫", names: ["male-teacher", ""]),
	Emoji(char: "👨‍🏭", names: ["male-factory-worker", ""]),
	Emoji(char: "👨‍👦‍👦", names: ["man-boy-boy", ""]),
	Emoji(char: "👨‍👦", names: ["man-boy", ""]),
	Emoji(char: "👨‍👧‍👦", names: ["man-girl-boy", ""]),
	Emoji(char: "👨‍👧‍👧", names: ["man-girl-girl", ""]),
	Emoji(char: "👨‍👧", names: ["man-girl", ""]),
	Emoji(char: "👨‍👨‍👦", names: ["man-man-boy", ""]),
	Emoji(char: "👨‍👨‍👦‍👦", names: ["man-man-boy-boy", ""]),
	Emoji(char: "👨‍👨‍👧", names: ["man-man-girl", ""]),
	Emoji(char: "👨‍👨‍👧‍👦", names: ["man-man-girl-boy", ""]),
	Emoji(char: "👨‍👨‍👧‍👧", names: ["man-man-girl-girl", ""]),
	Emoji(char: "👨‍👩‍👦", names: ["man-woman-boy", ""]),
	Emoji(char: "👨‍👩‍👦‍👦", names: ["man-woman-boy-boy", ""]),
	Emoji(char: "👨‍👩‍👧", names: ["man-woman-girl", ""]),
	Emoji(char: "👨‍👩‍👧‍👦", names: ["man-woman-girl-boy", ""]),
	Emoji(char: "👨‍👩‍👧‍👧", names: ["man-woman-girl-girl", ""]),
	Emoji(char: "👨‍💻", names: ["male-technologist", ""]),
	Emoji(char: "👨‍💼", names: ["male-office-worker", ""]),
	Emoji(char: "👨‍🔧", names: ["male-mechanic", ""]),
	Emoji(char: "👨‍🔬", names: ["male-scientist", ""]),
	Emoji(char: "👨‍🚀", names: ["male-astronaut", ""]),
	Emoji(char: "👨‍🚒", names: ["male-firefighter", ""]),
	Emoji(char: "👨‍⚕️", names: ["male-doctor", ""]),
	Emoji(char: "👨‍⚖️", names: ["male-judge", ""]),
	Emoji(char: "👨‍✈️", names: ["male-pilot", ""]),
	Emoji(char: "👨‍❤️‍👨", names: ["man-heart-man", ""]),
	Emoji(char: "👨‍❤️‍💋‍👨", names: ["man-kiss-man", ""]),
	Emoji(char: "👨", names: ["man"]),
	Emoji(char: "👩‍🌾", names: ["female-farmer", ""]),
	Emoji(char: "👩‍🍳", names: ["female-cook", ""]),
	Emoji(char: "👩‍🎓", names: ["female-student", ""]),
	Emoji(char: "👩‍🎤", names: ["female-singer", ""]),
	Emoji(char: "👩‍🎨", names: ["female-artist", ""]),
	Emoji(char: "👩‍🏫", names: ["female-teacher", ""]),
	Emoji(char: "👩‍🏭", names: ["female-factory-worker", ""]),
	Emoji(char: "👩‍👦‍👦", names: ["woman-boy-boy", ""]),
	Emoji(char: "👩‍👦", names: ["woman-boy", ""]),
	Emoji(char: "👩‍👧‍👦", names: ["woman-girl-boy", ""]),
	Emoji(char: "👩‍👧‍👧", names: ["woman-girl-girl", ""]),
	Emoji(char: "👩‍👧", names: ["woman-girl", ""]),
	Emoji(char: "👩‍👩‍👦", names: ["woman-woman-boy", ""]),
	Emoji(char: "👩‍👩‍👦‍👦", names: ["woman-woman-boy-boy", ""]),
	Emoji(char: "👩‍👩‍👧", names: ["woman-woman-girl", ""]),
	Emoji(char: "👩‍👩‍👧‍👦", names: ["woman-woman-girl-boy", ""]),
	Emoji(char: "👩‍👩‍👧‍👧", names: ["woman-woman-girl-girl", ""]),
	Emoji(char: "👩‍💻", names: ["female-technologist", ""]),
	Emoji(char: "👩‍💼", names: ["female-office-worker", ""]),
	Emoji(char: "👩‍🔧", names: ["female-mechanic", ""]),
	Emoji(char: "👩‍🔬", names: ["female-scientist", ""]),
	Emoji(char: "👩‍🚀", names: ["female-astronaut", ""]),
	Emoji(char: "👩‍🚒", names: ["female-firefighter", ""]),
	Emoji(char: "👩‍⚕️", names: ["female-doctor", ""]),
	Emoji(char: "👩‍⚖️", names: ["female-judge", ""]),
	Emoji(char: "👩‍✈️", names: ["female-pilot", ""]),
	Emoji(char: "👩‍❤️‍👨", names: ["woman-heart-man", ""]),
	Emoji(char: "👩‍❤️‍👩", names: ["woman-heart-woman", ""]),
	Emoji(char: "👩‍❤️‍💋‍👨", names: ["woman-kiss-man", ""]),
	Emoji(char: "👩‍❤️‍💋‍👩", names: ["woman-kiss-woman", ""]),
	Emoji(char: "👩", names: ["woman"]),
	Emoji(char: "👪", names: ["family"]),
	Emoji(char: "👫", names: ["couple", "man-and-woman-holding-hands"]),
	Emoji(char: "👬", names: ["two-men-holding-hands"]),
	Emoji(char: "👭", names: ["two-women-holding-hands"]),
	Emoji(char: "👮‍♀️", names: ["female-police-officer", ""]),
	Emoji(char: "👮‍♂️", names: ["male-police-officer", ""]),
	Emoji(char: "👮", names: ["cop", "police-officer"]),
	Emoji(char: "👯‍♀️", names: ["woman-with-bunny-ears-partying", ""]),
	Emoji(char: "👯‍♂️", names: ["man-with-bunny-ears-partying", ""]),
	Emoji(char: "👯", names: ["dancers", "woman-with-bunny-ears"]),
	Emoji(char: "👰", names: ["bride-with-veil"]),
	Emoji(char: "👱‍♀️", names: ["blond-haired-woman", ""]),
	Emoji(char: "👱‍♂️", names: ["blond-haired-man", ""]),
	Emoji(char: "👱", names: ["person-with-blond-hair"]),
	Emoji(char: "👲", names: ["man-with-gua-pi-mao"]),
	Emoji(char: "👳‍♀️", names: ["woman-wearing-turban", ""]),
	Emoji(char: "👳‍♂️", names: ["man-wearing-turban", ""]),
	Emoji(char: "👳", names: ["man-with-turban"]),
	Emoji(char: "👴", names: ["older-man"]),
	Emoji(char: "👵", names: ["older-woman"]),
	Emoji(char: "👶", names: ["baby"]),
	Emoji(char: "👷‍♀️", names: ["female-construction-worker", ""]),
	Emoji(char: "👷‍♂️", names: ["male-construction-worker", ""]),
	Emoji(char: "👷", names: ["construction-worker"]),
	Emoji(char: "👸", names: ["princess"]),
	Emoji(char: "👹", names: ["japanese-ogre"]),
	Emoji(char: "👺", names: ["japanese-goblin"]),
	Emoji(char: "👻", names: ["ghost"]),
	Emoji(char: "👼", names: ["angel", "baby-angel"]),
	Emoji(char: "👽", names: ["alien", "extraterrestrial-alien"]),
	Emoji(char: "👾", names: ["space-invader", "alien-monster"]),
	Emoji(char: "👿", names: ["imp"]),
	Emoji(char: "💀", names: ["skull"]),
	Emoji(char: "💁‍♀️", names: ["woman-tipping-hand", ""]),
	Emoji(char: "💁‍♂️", names: ["man-tipping-hand", ""]),
	Emoji(char: "💁", names: ["information-desk-person"]),
	Emoji(char: "💂‍♀️", names: ["female-guard", ""]),
	Emoji(char: "💂‍♂️", names: ["male-guard", ""]),
	Emoji(char: "💂", names: ["guardsman"]),
	Emoji(char: "💃", names: ["dancer"]),
	Emoji(char: "💄", names: ["lipstick"]),
	Emoji(char: "💅", names: ["nail-care", "nail-polish"]),
	Emoji(char: "💆‍♀️", names: ["woman-getting-massage", ""]),
	Emoji(char: "💆‍♂️", names: ["man-getting-massage", ""]),
	Emoji(char: "💆", names: ["massage", "face-massage"]),
	Emoji(char: "💇‍♀️", names: ["woman-getting-haircut", ""]),
	Emoji(char: "💇‍♂️", names: ["man-getting-haircut", ""]),
	Emoji(char: "💇", names: ["haircut"]),
	Emoji(char: "💈", names: ["barber", "barber-pole"]),
	Emoji(char: "💉", names: ["syringe"]),
	Emoji(char: "💊", names: ["pill"]),
	Emoji(char: "💋", names: ["kiss", "kiss-mark"]),
	Emoji(char: "💌", names: ["love-letter"]),
	Emoji(char: "💍", names: ["ring"]),
	Emoji(char: "💎", names: ["gem", "gem-stone"]),
	Emoji(char: "💏", names: ["couplekiss", "kiss"]),
	Emoji(char: "💐", names: ["bouquet"]),
	Emoji(char: "💑", names: ["couple-with-heart"]),
	Emoji(char: "💒", names: ["wedding"]),
	Emoji(char: "💓", names: ["heartbeat", "beating-heart"]),
	Emoji(char: "💔", names: ["broken-heart"]),
	Emoji(char: "💕", names: ["two-hearts"]),
	Emoji(char: "💖", names: ["sparkling-heart"]),
	Emoji(char: "💗", names: ["heartpulse", "growing-heart"]),
	Emoji(char: "💘", names: ["cupid", "heart-with-arrow"]),
	Emoji(char: "💙", names: ["blue-heart"]),
	Emoji(char: "💚", names: ["green-heart"]),
	Emoji(char: "💛", names: ["yellow-heart"]),
	Emoji(char: "💜", names: ["purple-heart"]),
	Emoji(char: "💝", names: ["gift-heart", "heart-with-ribbon"]),
	Emoji(char: "💞", names: ["revolving-hearts"]),
	Emoji(char: "💟", names: ["heart-decoration"]),
	Emoji(char: "💠", names: ["diamond-shape-with-a-dot-inside"]),
	Emoji(char: "💡", names: ["bulb", "electric-light-bulb"]),
	Emoji(char: "💢", names: ["anger", "anger-symbol"]),
	Emoji(char: "💣", names: ["bomb"]),
	Emoji(char: "💤", names: ["zzz", "sleeping-symbol"]),
	Emoji(char: "💥", names: ["boom", "collision-symbol"]),
	Emoji(char: "💦", names: ["sweat-drops", "splashing-sweat-symbol"]),
	Emoji(char: "💧", names: ["droplet"]),
	Emoji(char: "💨", names: ["dash", "dash-symbol"]),
	Emoji(char: "💩", names: ["hankey", "pile-of-poo"]),
	Emoji(char: "💪", names: ["muscle", "flexed-biceps"]),
	Emoji(char: "💫", names: ["dizzy", "dizzy-symbol"]),
	Emoji(char: "💬", names: ["speech-balloon"]),
	Emoji(char: "💭", names: ["thought-balloon"]),
	Emoji(char: "💮", names: ["white-flower"]),
	Emoji(char: "💯", names: ["100", "hundred-points-symbol"]),
	Emoji(char: "💰", names: ["moneybag", "money-bag"]),
	Emoji(char: "💱", names: ["currency-exchange"]),
	Emoji(char: "💲", names: ["heavy-dollar-sign"]),
	Emoji(char: "💳", names: ["credit-card"]),
	Emoji(char: "💴", names: ["yen", "banknote-with-yen-sign"]),
	Emoji(char: "💵", names: ["dollar", "banknote-with-dollar-sign"]),
	Emoji(char: "💶", names: ["euro", "banknote-with-euro-sign"]),
	Emoji(char: "💷", names: ["pound", "banknote-with-pound-sign"]),
	Emoji(char: "💸", names: ["money-with-wings"]),
	Emoji(char: "💹", names: ["chart", "chart-with-upwards-trend-and-yen-sign"]),
	Emoji(char: "💺", names: ["seat"]),
	Emoji(char: "💻", names: ["computer", "personal-computer"]),
	Emoji(char: "💼", names: ["briefcase"]),
	Emoji(char: "💽", names: ["minidisc"]),
	Emoji(char: "💾", names: ["floppy-disk"]),
	Emoji(char: "💿", names: ["cd", "optical-disc"]),
	Emoji(char: "📀", names: ["dvd"]),
	Emoji(char: "📁", names: ["file-folder"]),
	Emoji(char: "📂", names: ["open-file-folder"]),
	Emoji(char: "📃", names: ["page-with-curl"]),
	Emoji(char: "📄", names: ["page-facing-up"]),
	Emoji(char: "📅", names: ["date", "calendar"]),
	Emoji(char: "📆", names: ["calendar", "tear-off-calendar"]),
	Emoji(char: "📇", names: ["card-index"]),
	Emoji(char: "📈", names: ["chart-with-upwards-trend"]),
	Emoji(char: "📉", names: ["chart-with-downwards-trend"]),
	Emoji(char: "📊", names: ["bar-chart"]),
	Emoji(char: "📋", names: ["clipboard"]),
	Emoji(char: "📌", names: ["pushpin"]),
	Emoji(char: "📍", names: ["round-pushpin"]),
	Emoji(char: "📎", names: ["paperclip"]),
	Emoji(char: "📏", names: ["straight-ruler"]),
	Emoji(char: "📐", names: ["triangular-ruler"]),
	Emoji(char: "📑", names: ["bookmark-tabs"]),
	Emoji(char: "📒", names: ["ledger"]),
	Emoji(char: "📓", names: ["notebook"]),
	Emoji(char: "📔", names: ["notebook-with-decorative-cover"]),
	Emoji(char: "📕", names: ["closed-book"]),
	Emoji(char: "📖", names: ["book", "open-book"]),
	Emoji(char: "📗", names: ["green-book"]),
	Emoji(char: "📘", names: ["blue-book"]),
	Emoji(char: "📙", names: ["orange-book"]),
	Emoji(char: "📚", names: ["books"]),
	Emoji(char: "📛", names: ["name-badge"]),
	Emoji(char: "📜", names: ["scroll"]),
	Emoji(char: "📝", names: ["memo"]),
	Emoji(char: "📞", names: ["telephone-receiver"]),
	Emoji(char: "📟", names: ["pager"]),
	Emoji(char: "📠", names: ["fax", "fax-machine"]),
	Emoji(char: "📡", names: ["satellite-antenna"]),
	Emoji(char: "📢", names: ["loudspeaker", "public-address-loudspeaker"]),
	Emoji(char: "📣", names: ["mega", "cheering-megaphone"]),
	Emoji(char: "📤", names: ["outbox-tray"]),
	Emoji(char: "📥", names: ["inbox-tray"]),
	Emoji(char: "📦", names: ["package"]),
	Emoji(char: "📧", names: ["e-mail", "e-mail-symbol"]),
	Emoji(char: "📨", names: ["incoming-envelope"]),
	Emoji(char: "📩", names: ["envelope-with-arrow", "envelope-with-downwards-arrow-above"]),
	Emoji(char: "📪", names: ["mailbox-closed", "closed-mailbox-with-lowered-flag"]),
	Emoji(char: "📫", names: ["mailbox", "closed-mailbox-with-raised-flag"]),
	Emoji(char: "📬", names: ["mailbox-with-mail", "open-mailbox-with-raised-flag"]),
	Emoji(char: "📭", names: ["mailbox-with-no-mail", "open-mailbox-with-lowered-flag"]),
	Emoji(char: "📮", names: ["postbox"]),
	Emoji(char: "📯", names: ["postal-horn"]),
	Emoji(char: "📰", names: ["newspaper"]),
	Emoji(char: "📱", names: ["iphone", "mobile-phone"]),
	Emoji(char: "📲", names: ["calling", "mobile-phone-with-rightwards-arrow-at-left"]),
	Emoji(char: "📳", names: ["vibration-mode"]),
	Emoji(char: "📴", names: ["mobile-phone-off"]),
	Emoji(char: "📵", names: ["no-mobile-phones"]),
	Emoji(char: "📶", names: ["signal-strength", "antenna-with-bars"]),
	Emoji(char: "📷", names: ["camera"]),
	Emoji(char: "📸", names: ["camera-with-flash"]),
	Emoji(char: "📹", names: ["video-camera"]),
	Emoji(char: "📺", names: ["tv", "television"]),
	Emoji(char: "📻", names: ["radio"]),
	Emoji(char: "📼", names: ["vhs", "videocassette"]),
	Emoji(char: "📽️", names: ["film-projector", ""]),
	Emoji(char: "📿", names: ["prayer-beads"]),
	Emoji(char: "🔀", names: ["twisted-rightwards-arrows"]),
	Emoji(char: "🔁", names: ["repeat", "clockwise-rightwards-and-leftwards-open-circle-arrows"]),
	Emoji(char: "🔂", names: ["repeat-one", "clockwise-rightwards-and-leftwards-open-circle-arrows-with-circled-one-overlay"]),
	Emoji(char: "🔃", names: ["arrows-clockwise", "clockwise-downwards-and-upwards-open-circle-arrows"]),
	Emoji(char: "🔄", names: ["arrows-counterclockwise", "anticlockwise-downwards-and-upwards-open-circle-arrows"]),
	Emoji(char: "🔅", names: ["low-brightness", "low-brightness-symbol"]),
	Emoji(char: "🔆", names: ["high-brightness", "high-brightness-symbol"]),
	Emoji(char: "🔇", names: ["mute", "speaker-with-cancellation-stroke"]),
	Emoji(char: "🔈", names: ["speaker"]),
	Emoji(char: "🔉", names: ["sound", "speaker-with-one-sound-wave"]),
	Emoji(char: "🔊", names: ["loud-sound", "speaker-with-three-sound-waves"]),
	Emoji(char: "🔋", names: ["battery"]),
	Emoji(char: "🔌", names: ["electric-plug"]),
	Emoji(char: "🔍", names: ["mag", "left-pointing-magnifying-glass"]),
	Emoji(char: "🔎", names: ["mag-right", "right-pointing-magnifying-glass"]),
	Emoji(char: "🔏", names: ["lock-with-ink-pen"]),
	Emoji(char: "🔐", names: ["closed-lock-with-key"]),
	Emoji(char: "🔑", names: ["key"]),
	Emoji(char: "🔒", names: ["lock"]),
	Emoji(char: "🔓", names: ["unlock", "open-lock"]),
	Emoji(char: "🔔", names: ["bell"]),
	Emoji(char: "🔕", names: ["no-bell", "bell-with-cancellation-stroke"]),
	Emoji(char: "🔖", names: ["bookmark"]),
	Emoji(char: "🔗", names: ["link", "link-symbol"]),
	Emoji(char: "🔘", names: ["radio-button"]),
	Emoji(char: "🔙", names: ["back", "back-with-leftwards-arrow-above"]),
	Emoji(char: "🔚", names: ["end", "end-with-leftwards-arrow-above"]),
	Emoji(char: "🔛", names: ["on", "on-with-exclamation-mark-with-left-right-arrow-above"]),
	Emoji(char: "🔜", names: ["soon", "soon-with-rightwards-arrow-above"]),
	Emoji(char: "🔝", names: ["top", "top-with-upwards-arrow-above"]),
	Emoji(char: "🔞", names: ["underage", "no-one-under-eighteen-symbol"]),
	Emoji(char: "🔟", names: ["keycap-ten"]),
	Emoji(char: "🔠", names: ["capital-abcd", "input-symbol-for-latin-capital-letters"]),
	Emoji(char: "🔡", names: ["abcd", "input-symbol-for-latin-small-letters"]),
	Emoji(char: "🔢", names: ["1234", "input-symbol-for-numbers"]),
	Emoji(char: "🔣", names: ["symbols", "input-symbol-for-symbols"]),
	Emoji(char: "🔤", names: ["abc", "input-symbol-for-latin-letters"]),
	Emoji(char: "🔥", names: ["fire"]),
	Emoji(char: "🔦", names: ["flashlight", "electric-torch"]),
	Emoji(char: "🔧", names: ["wrench"]),
	Emoji(char: "🔨", names: ["hammer"]),
	Emoji(char: "🔩", names: ["nut-and-bolt"]),
	Emoji(char: "🔪", names: ["hocho"]),
	Emoji(char: "🔫", names: ["gun", "pistol"]),
	Emoji(char: "🔬", names: ["microscope"]),
	Emoji(char: "🔭", names: ["telescope"]),
	Emoji(char: "🔮", names: ["crystal-ball"]),
	Emoji(char: "🔯", names: ["six-pointed-star", "six-pointed-star-with-middle-dot"]),
	Emoji(char: "🔰", names: ["beginner", "japanese-symbol-for-beginner"]),
	Emoji(char: "🔱", names: ["trident", "trident-emblem"]),
	Emoji(char: "🔲", names: ["black-square-button"]),
	Emoji(char: "🔳", names: ["white-square-button"]),
	Emoji(char: "🔴", names: ["red-circle", "large-red-circle"]),
	Emoji(char: "🔵", names: ["large-blue-circle"]),
	Emoji(char: "🔶", names: ["large-orange-diamond"]),
	Emoji(char: "🔷", names: ["large-blue-diamond"]),
	Emoji(char: "🔸", names: ["small-orange-diamond"]),
	Emoji(char: "🔹", names: ["small-blue-diamond"]),
	Emoji(char: "🔺", names: ["small-red-triangle", "up-pointing-red-triangle"]),
	Emoji(char: "🔻", names: ["small-red-triangle-down", "down-pointing-red-triangle"]),
	Emoji(char: "🔼", names: ["arrow-up-small", "up-pointing-small-red-triangle"]),
	Emoji(char: "🔽", names: ["arrow-down-small", "down-pointing-small-red-triangle"]),
	Emoji(char: "🕉️", names: ["om-symbol", ""]),
	Emoji(char: "🕊️", names: ["dove-of-peace", ""]),
	Emoji(char: "🕋", names: ["kaaba"]),
	Emoji(char: "🕌", names: ["mosque"]),
	Emoji(char: "🕍", names: ["synagogue"]),
	Emoji(char: "🕎", names: ["menorah-with-nine-branches"]),
	Emoji(char: "🕐", names: ["clock1", "clock-face-one-oclock"]),
	Emoji(char: "🕑", names: ["clock2", "clock-face-two-oclock"]),
	Emoji(char: "🕒", names: ["clock3", "clock-face-three-oclock"]),
	Emoji(char: "🕓", names: ["clock4", "clock-face-four-oclock"]),
	Emoji(char: "🕔", names: ["clock5", "clock-face-five-oclock"]),
	Emoji(char: "🕕", names: ["clock6", "clock-face-six-oclock"]),
	Emoji(char: "🕖", names: ["clock7", "clock-face-seven-oclock"]),
	Emoji(char: "🕗", names: ["clock8", "clock-face-eight-oclock"]),
	Emoji(char: "🕘", names: ["clock9", "clock-face-nine-oclock"]),
	Emoji(char: "🕙", names: ["clock10", "clock-face-ten-oclock"]),
	Emoji(char: "🕚", names: ["clock11", "clock-face-eleven-oclock"]),
	Emoji(char: "🕛", names: ["clock12", "clock-face-twelve-oclock"]),
	Emoji(char: "🕜", names: ["clock130", "clock-face-one-thirty"]),
	Emoji(char: "🕝", names: ["clock230", "clock-face-two-thirty"]),
	Emoji(char: "🕞", names: ["clock330", "clock-face-three-thirty"]),
	Emoji(char: "🕟", names: ["clock430", "clock-face-four-thirty"]),
	Emoji(char: "🕠", names: ["clock530", "clock-face-five-thirty"]),
	Emoji(char: "🕡", names: ["clock630", "clock-face-six-thirty"]),
	Emoji(char: "🕢", names: ["clock730", "clock-face-seven-thirty"]),
	Emoji(char: "🕣", names: ["clock830", "clock-face-eight-thirty"]),
	Emoji(char: "🕤", names: ["clock930", "clock-face-nine-thirty"]),
	Emoji(char: "🕥", names: ["clock1030", "clock-face-ten-thirty"]),
	Emoji(char: "🕦", names: ["clock1130", "clock-face-eleven-thirty"]),
	Emoji(char: "🕧", names: ["clock1230", "clock-face-twelve-thirty"]),
	Emoji(char: "🕯️", names: ["candle", ""]),
	Emoji(char: "🕰️", names: ["mantelpiece-clock", ""]),
	Emoji(char: "🕳️", names: ["hole", ""]),
	Emoji(char: "🕴️", names: ["man-in-business-suit-levitating", ""]),
	Emoji(char: "🕵️‍♀️", names: ["female-detective", ""]),
	Emoji(char: "🕵️‍♂️", names: ["male-detective", ""]),
	Emoji(char: "🕵️", names: ["sleuth-or-spy", ""]),
	Emoji(char: "🕶️", names: ["dark-sunglasses", ""]),
	Emoji(char: "🕷️", names: ["spider", ""]),
	Emoji(char: "🕸️", names: ["spider-web", ""]),
	Emoji(char: "🕹️", names: ["joystick", ""]),
	Emoji(char: "🕺", names: ["man-dancing"]),
	Emoji(char: "🖇️", names: ["linked-paperclips", ""]),
	Emoji(char: "🖊️", names: ["lower-left-ballpoint-pen", ""]),
	Emoji(char: "🖋️", names: ["lower-left-fountain-pen", ""]),
	Emoji(char: "🖌️", names: ["lower-left-paintbrush", ""]),
	Emoji(char: "🖍️", names: ["lower-left-crayon", ""]),
	Emoji(char: "🖐️", names: ["raised-hand-with-fingers-splayed", ""]),
	Emoji(char: "🖕", names: ["middle-finger", "reversed-hand-with-middle-finger-extended"]),
	Emoji(char: "🖖", names: ["spock-hand", "raised-hand-with-part-between-middle-and-ring-fingers"]),
	Emoji(char: "🖤", names: ["black-heart"]),
	Emoji(char: "🖥️", names: ["desktop-computer", ""]),
	Emoji(char: "🖨️", names: ["printer", ""]),
	Emoji(char: "🖱️", names: ["three-button-mouse", ""]),
	Emoji(char: "🖲️", names: ["trackball", ""]),
	Emoji(char: "🖼️", names: ["frame-with-picture", ""]),
	Emoji(char: "🗂️", names: ["card-index-dividers", ""]),
	Emoji(char: "🗃️", names: ["card-file-box", ""]),
	Emoji(char: "🗄️", names: ["file-cabinet", ""]),
	Emoji(char: "🗑️", names: ["wastebasket", ""]),
	Emoji(char: "🗒️", names: ["spiral-note-pad", ""]),
	Emoji(char: "🗓️", names: ["spiral-calendar-pad", ""]),
	Emoji(char: "🗜️", names: ["compression", ""]),
	Emoji(char: "🗝️", names: ["old-key", ""]),
	Emoji(char: "🗞️", names: ["rolled-up-newspaper", ""]),
	Emoji(char: "🗡️", names: ["dagger-knife", ""]),
	Emoji(char: "🗣️", names: ["speaking-head-in-silhouette", ""]),
	Emoji(char: "🗨️", names: ["left-speech-bubble", ""]),
	Emoji(char: "🗯️", names: ["right-anger-bubble", ""]),
	Emoji(char: "🗳️", names: ["ballot-box-with-ballot", ""]),
	Emoji(char: "🗺️", names: ["world-map", ""]),
	Emoji(char: "🗻", names: ["mount-fuji"]),
	Emoji(char: "🗼", names: ["tokyo-tower"]),
	Emoji(char: "🗽", names: ["statue-of-liberty"]),
	Emoji(char: "🗾", names: ["japan", "silhouette-of-japan"]),
	Emoji(char: "🗿", names: ["moyai"]),
	Emoji(char: "😀", names: ["grinning", "grinning-face"]),
	Emoji(char: "😁", names: ["grin", "grinning-face-with-smiling-eyes"]),
	Emoji(char: "😂", names: ["joy", "face-with-tears-of-joy"]),
	Emoji(char: "😃", names: ["smiley", "smiling-face-with-open-mouth"]),
	Emoji(char: "😄", names: ["smile", "smiling-face-with-open-mouth-and-smiling-eyes"]),
	Emoji(char: "😅", names: ["sweat-smile", "smiling-face-with-open-mouth-and-cold-sweat"]),
	Emoji(char: "😆", names: ["laughing", "smiling-face-with-open-mouth-and-tightly-closed-eyes"]),
	Emoji(char: "😇", names: ["innocent", "smiling-face-with-halo"]),
	Emoji(char: "😈", names: ["smiling-imp", "smiling-face-with-horns"]),
	Emoji(char: "😉", names: ["wink", "winking-face"]),
	Emoji(char: "😊", names: ["blush", "smiling-face-with-smiling-eyes"]),
	Emoji(char: "😋", names: ["yum", "face-savouring-delicious-food"]),
	Emoji(char: "😌", names: ["relieved", "relieved-face"]),
	Emoji(char: "😍", names: ["heart-eyes", "smiling-face-with-heart-shaped-eyes"]),
	Emoji(char: "😎", names: ["sunglasses", "smiling-face-with-sunglasses"]),
	Emoji(char: "😏", names: ["smirk", "smirking-face"]),
	Emoji(char: "😐", names: ["neutral-face"]),
	Emoji(char: "😑", names: ["expressionless", "expressionless-face"]),
	Emoji(char: "😒", names: ["unamused", "unamused-face"]),
	Emoji(char: "😓", names: ["sweat", "face-with-cold-sweat"]),
	Emoji(char: "😔", names: ["pensive", "pensive-face"]),
	Emoji(char: "😕", names: ["confused", "confused-face"]),
	Emoji(char: "😖", names: ["confounded", "confounded-face"]),
	Emoji(char: "😗", names: ["kissing", "kissing-face"]),
	Emoji(char: "😘", names: ["kissing-heart", "face-throwing-a-kiss"]),
	Emoji(char: "😙", names: ["kissing-smiling-eyes", "kissing-face-with-smiling-eyes"]),
	Emoji(char: "😚", names: ["kissing-closed-eyes", "kissing-face-with-closed-eyes"]),
	Emoji(char: "😛", names: ["stuck-out-tongue", "face-with-stuck-out-tongue"]),
	Emoji(char: "😜", names: ["stuck-out-tongue-winking-eye", "face-with-stuck-out-tongue-and-winking-eye"]),
	Emoji(char: "😝", names: ["stuck-out-tongue-closed-eyes", "face-with-stuck-out-tongue-and-tightly-closed-eyes"]),
	Emoji(char: "😞", names: ["disappointed", "disappointed-face"]),
	Emoji(char: "😟", names: ["worried", "worried-face"]),
	Emoji(char: "😠", names: ["angry", "angry-face"]),
	Emoji(char: "😡", names: ["rage", "pouting-face"]),
	Emoji(char: "😢", names: ["cry", "crying-face"]),
	Emoji(char: "😣", names: ["persevere", "persevering-face"]),
	Emoji(char: "😤", names: ["triumph", "face-with-look-of-triumph"]),
	Emoji(char: "😥", names: ["disappointed-relieved", "disappointed-but-relieved-face"]),
	Emoji(char: "😦", names: ["frowning", "frowning-face-with-open-mouth"]),
	Emoji(char: "😧", names: ["anguished", "anguished-face"]),
	Emoji(char: "😨", names: ["fearful", "fearful-face"]),
	Emoji(char: "😩", names: ["weary", "weary-face"]),
	Emoji(char: "😪", names: ["sleepy", "sleepy-face"]),
	Emoji(char: "😫", names: ["tired-face"]),
	Emoji(char: "😬", names: ["grimacing", "grimacing-face"]),
	Emoji(char: "😭", names: ["sob", "loudly-crying-face"]),
	Emoji(char: "😮", names: ["open-mouth", "face-with-open-mouth"]),
	Emoji(char: "😯", names: ["hushed", "hushed-face"]),
	Emoji(char: "😰", names: ["cold-sweat", "face-with-open-mouth-and-cold-sweat"]),
	Emoji(char: "😱", names: ["scream", "face-screaming-in-fear"]),
	Emoji(char: "😲", names: ["astonished", "astonished-face"]),
	Emoji(char: "😳", names: ["flushed", "flushed-face"]),
	Emoji(char: "😴", names: ["sleeping", "sleeping-face"]),
	Emoji(char: "😵", names: ["dizzy-face"]),
	Emoji(char: "😶", names: ["no-mouth", "face-without-mouth"]),
	Emoji(char: "😷", names: ["mask", "face-with-medical-mask"]),
	Emoji(char: "😸", names: ["smile-cat", "grinning-cat-face-with-smiling-eyes"]),
	Emoji(char: "😹", names: ["joy-cat", "cat-face-with-tears-of-joy"]),
	Emoji(char: "😺", names: ["smiley-cat", "smiling-cat-face-with-open-mouth"]),
	Emoji(char: "😻", names: ["heart-eyes-cat", "smiling-cat-face-with-heart-shaped-eyes"]),
	Emoji(char: "😼", names: ["smirk-cat", "cat-face-with-wry-smile"]),
	Emoji(char: "😽", names: ["kissing-cat", "kissing-cat-face-with-closed-eyes"]),
	Emoji(char: "😾", names: ["pouting-cat", "pouting-cat-face"]),
	Emoji(char: "😿", names: ["crying-cat-face"]),
	Emoji(char: "🙀", names: ["scream-cat", "weary-cat-face"]),
	Emoji(char: "🙁", names: ["slightly-frowning-face"]),
	Emoji(char: "🙂", names: ["slightly-smiling-face"]),
	Emoji(char: "🙃", names: ["upside-down-face"]),
	Emoji(char: "🙄", names: ["face-with-rolling-eyes"]),
	Emoji(char: "🙅‍♀️", names: ["woman-gesturing-no", ""]),
	Emoji(char: "🙅‍♂️", names: ["man-gesturing-no", ""]),
	Emoji(char: "🙅", names: ["no-good", "face-with-no-good-gesture"]),
	Emoji(char: "🙆‍♀️", names: ["woman-gesturing-ok", ""]),
	Emoji(char: "🙆‍♂️", names: ["man-gesturing-ok", ""]),
	Emoji(char: "🙆", names: ["ok-woman", "face-with-ok-gesture"]),
	Emoji(char: "🙇‍♀️", names: ["woman-bowing", ""]),
	Emoji(char: "🙇‍♂️", names: ["man-bowing", ""]),
	Emoji(char: "🙇", names: ["bow", "person-bowing-deeply"]),
	Emoji(char: "🙈", names: ["see-no-evil", "see-no-evil-monkey"]),
	Emoji(char: "🙉", names: ["hear-no-evil", "hear-no-evil-monkey"]),
	Emoji(char: "🙊", names: ["speak-no-evil", "speak-no-evil-monkey"]),
	Emoji(char: "🙋‍♀️", names: ["woman-raising-hand", ""]),
	Emoji(char: "🙋‍♂️", names: ["man-raising-hand", ""]),
	Emoji(char: "🙋", names: ["raising-hand", "happy-person-raising-one-hand"]),
	Emoji(char: "🙌", names: ["raised-hands", "person-raising-both-hands-in-celebration"]),
	Emoji(char: "🙍‍♀️", names: ["woman-frowning", ""]),
	Emoji(char: "🙍‍♂️", names: ["man-frowning", ""]),
	Emoji(char: "🙍", names: ["person-frowning"]),
	Emoji(char: "🙎‍♀️", names: ["woman-pouting", ""]),
	Emoji(char: "🙎‍♂️", names: ["man-pouting", ""]),
	Emoji(char: "🙎", names: ["person-with-pouting-face"]),
	Emoji(char: "🙏", names: ["pray", "person-with-folded-hands"]),
	Emoji(char: "🚀", names: ["rocket"]),
	Emoji(char: "🚁", names: ["helicopter"]),
	Emoji(char: "🚂", names: ["steam-locomotive"]),
	Emoji(char: "🚃", names: ["railway-car"]),
	Emoji(char: "🚄", names: ["bullettrain-side", "high-speed-train"]),
	Emoji(char: "🚅", names: ["bullettrain-front", "high-speed-train-with-bullet-nose"]),
	Emoji(char: "🚆", names: ["train2", "train"]),
	Emoji(char: "🚇", names: ["metro"]),
	Emoji(char: "🚈", names: ["light-rail"]),
	Emoji(char: "🚉", names: ["station"]),
	Emoji(char: "🚊", names: ["tram"]),
	Emoji(char: "🚋", names: ["train", "tram-car"]),
	Emoji(char: "🚌", names: ["bus"]),
	Emoji(char: "🚍", names: ["oncoming-bus"]),
	Emoji(char: "🚎", names: ["trolleybus"]),
	Emoji(char: "🚏", names: ["busstop", "bus-stop"]),
	Emoji(char: "🚐", names: ["minibus"]),
	Emoji(char: "🚑", names: ["ambulance"]),
	Emoji(char: "🚒", names: ["fire-engine"]),
	Emoji(char: "🚓", names: ["police-car"]),
	Emoji(char: "🚔", names: ["oncoming-police-car"]),
	Emoji(char: "🚕", names: ["taxi"]),
	Emoji(char: "🚖", names: ["oncoming-taxi"]),
	Emoji(char: "🚗", names: ["car", "automobile"]),
	Emoji(char: "🚘", names: ["oncoming-automobile"]),
	Emoji(char: "🚙", names: ["blue-car", "recreational-vehicle"]),
	Emoji(char: "🚚", names: ["truck", "delivery-truck"]),
	Emoji(char: "🚛", names: ["articulated-lorry"]),
	Emoji(char: "🚜", names: ["tractor"]),
	Emoji(char: "🚝", names: ["monorail"]),
	Emoji(char: "🚞", names: ["mountain-railway"]),
	Emoji(char: "🚟", names: ["suspension-railway"]),
	Emoji(char: "🚠", names: ["mountain-cableway"]),
	Emoji(char: "🚡", names: ["aerial-tramway"]),
	Emoji(char: "🚢", names: ["ship"]),
	Emoji(char: "🚣‍♀️", names: ["woman-rowing-boat", ""]),
	Emoji(char: "🚣‍♂️", names: ["man-rowing-boat", ""]),
	Emoji(char: "🚣", names: ["rowboat"]),
	Emoji(char: "🚤", names: ["speedboat"]),
	Emoji(char: "🚥", names: ["traffic-light", "horizontal-traffic-light"]),
	Emoji(char: "🚦", names: ["vertical-traffic-light"]),
	Emoji(char: "🚧", names: ["construction", "construction-sign"]),
	Emoji(char: "🚨", names: ["rotating-light", "police-cars-revolving-light"]),
	Emoji(char: "🚩", names: ["triangular-flag-on-post"]),
	Emoji(char: "🚪", names: ["door"]),
	Emoji(char: "🚫", names: ["no-entry-sign"]),
	Emoji(char: "🚬", names: ["smoking", "smoking-symbol"]),
	Emoji(char: "🚭", names: ["no-smoking", "no-smoking-symbol"]),
	Emoji(char: "🚮", names: ["put-litter-in-its-place", "put-litter-in-its-place-symbol"]),
	Emoji(char: "🚯", names: ["do-not-litter", "do-not-litter-symbol"]),
	Emoji(char: "🚰", names: ["potable-water", "potable-water-symbol"]),
	Emoji(char: "🚱", names: ["non-potable-water", "non-potable-water-symbol"]),
	Emoji(char: "🚲", names: ["bike", "bicycle"]),
	Emoji(char: "🚳", names: ["no-bicycles"]),
	Emoji(char: "🚴‍♀️", names: ["woman-biking", ""]),
	Emoji(char: "🚴‍♂️", names: ["man-biking", ""]),
	Emoji(char: "🚴", names: ["bicyclist"]),
	Emoji(char: "🚵‍♀️", names: ["woman-mountain-biking", ""]),
	Emoji(char: "🚵‍♂️", names: ["man-mountain-biking", ""]),
	Emoji(char: "🚵", names: ["mountain-bicyclist"]),
	Emoji(char: "🚶‍♀️", names: ["woman-walking", ""]),
	Emoji(char: "🚶‍♂️", names: ["man-walking", ""]),
	Emoji(char: "🚶", names: ["walking", "pedestrian"]),
	Emoji(char: "🚷", names: ["no-pedestrians"]),
	Emoji(char: "🚸", names: ["children-crossing"]),
	Emoji(char: "🚹", names: ["mens", "mens-symbol"]),
	Emoji(char: "🚺", names: ["womens", "womens-symbol"]),
	Emoji(char: "🚻", names: ["restroom"]),
	Emoji(char: "🚼", names: ["baby-symbol"]),
	Emoji(char: "🚽", names: ["toilet"]),
	Emoji(char: "🚾", names: ["wc", "water-closet"]),
	Emoji(char: "🚿", names: ["shower"]),
	Emoji(char: "🛀", names: ["bath"]),
	Emoji(char: "🛁", names: ["bathtub"]),
	Emoji(char: "🛂", names: ["passport-control"]),
	Emoji(char: "🛃", names: ["customs"]),
	Emoji(char: "🛄", names: ["baggage-claim"]),
	Emoji(char: "🛅", names: ["left-luggage"]),
	Emoji(char: "🛋️", names: ["couch-and-lamp", ""]),
	Emoji(char: "🛌", names: ["sleeping-accommodation"]),
	Emoji(char: "🛍️", names: ["shopping-bags", ""]),
	Emoji(char: "🛎️", names: ["bellhop-bell", ""]),
	Emoji(char: "🛏️", names: ["bed", ""]),
	Emoji(char: "🛐", names: ["place-of-worship"]),
	Emoji(char: "🛑", names: ["octagonal-sign"]),
	Emoji(char: "🛒", names: ["shopping-trolley"]),
	Emoji(char: "🛠️", names: ["hammer-and-wrench", ""]),
	Emoji(char: "🛡️", names: ["shield", ""]),
	Emoji(char: "🛢️", names: ["oil-drum", ""]),
	Emoji(char: "🛣️", names: ["motorway", ""]),
	Emoji(char: "🛤️", names: ["railway-track", ""]),
	Emoji(char: "🛥️", names: ["motor-boat", ""]),
	Emoji(char: "🛩️", names: ["small-airplane", ""]),
	Emoji(char: "🛫", names: ["airplane-departure"]),
	Emoji(char: "🛬", names: ["airplane-arriving"]),
	Emoji(char: "🛰️", names: ["satellite", ""]),
	Emoji(char: "🛳️", names: ["passenger-ship", ""]),
	Emoji(char: "🛴", names: ["scooter"]),
	Emoji(char: "🛵", names: ["motor-scooter"]),
	Emoji(char: "🛶", names: ["canoe"]),
	Emoji(char: "🛷", names: ["sled"]),
	Emoji(char: "🛸", names: ["flying-saucer"]),
	Emoji(char: "🤐", names: ["zipper-mouth-face"]),
	Emoji(char: "🤑", names: ["money-mouth-face"]),
	Emoji(char: "🤒", names: ["face-with-thermometer"]),
	Emoji(char: "🤓", names: ["nerd-face"]),
	Emoji(char: "🤔", names: ["thinking-face"]),
	Emoji(char: "🤕", names: ["face-with-head-bandage"]),
	Emoji(char: "🤖", names: ["robot-face"]),
	Emoji(char: "🤗", names: ["hugging-face"]),
	Emoji(char: "🤘", names: ["the-horns", "sign-of-the-horns"]),
	Emoji(char: "🤙", names: ["call-me-hand"]),
	Emoji(char: "🤚", names: ["raised-back-of-hand"]),
	Emoji(char: "🤛", names: ["left-facing-fist"]),
	Emoji(char: "🤜", names: ["right-facing-fist"]),
	Emoji(char: "🤝", names: ["handshake"]),
	Emoji(char: "🤞", names: ["hand-with-index-and-middle-fingers-crossed"]),
	Emoji(char: "🤟", names: ["i-love-you-hand-sign"]),
	Emoji(char: "🤠", names: ["face-with-cowboy-hat"]),
	Emoji(char: "🤡", names: ["clown-face"]),
	Emoji(char: "🤢", names: ["nauseated-face"]),
	Emoji(char: "🤣", names: ["rolling-on-the-floor-laughing"]),
	Emoji(char: "🤤", names: ["drooling-face"]),
	Emoji(char: "🤥", names: ["lying-face"]),
	Emoji(char: "🤦‍♀️", names: ["woman-facepalming", ""]),
	Emoji(char: "🤦‍♂️", names: ["man-facepalming", ""]),
	Emoji(char: "🤦", names: ["face-palm"]),
	Emoji(char: "🤧", names: ["sneezing-face"]),
	Emoji(char: "🤨", names: ["face-with-one-eyebrow-raised"]),
	Emoji(char: "🤩", names: ["grinning-face-with-star-eyes"]),
	Emoji(char: "🤪", names: ["grinning-face-with-one-large-and-one-small-eye"]),
	Emoji(char: "🤫", names: ["face-with-finger-covering-closed-lips"]),
	Emoji(char: "🤬", names: ["serious-face-with-symbols-covering-mouth"]),
	Emoji(char: "🤭", names: ["smiling-face-with-smiling-eyes-and-hand-covering-mouth"]),
	Emoji(char: "🤮", names: ["face-with-open-mouth-vomiting"]),
	Emoji(char: "🤯", names: ["shocked-face-with-exploding-head"]),
	Emoji(char: "🤰", names: ["pregnant-woman"]),
	Emoji(char: "🤱", names: ["breast-feeding"]),
	Emoji(char: "🤲", names: ["palms-up-together"]),
	Emoji(char: "🤳", names: ["selfie"]),
	Emoji(char: "🤴", names: ["prince"]),
	Emoji(char: "🤵", names: ["man-in-tuxedo"]),
	Emoji(char: "🤶", names: ["mother-christmas"]),
	Emoji(char: "🤷‍♀️", names: ["woman-shrugging", ""]),
	Emoji(char: "🤷‍♂️", names: ["man-shrugging", ""]),
	Emoji(char: "🤷", names: ["shrug"]),
	Emoji(char: "🤸‍♀️", names: ["woman-cartwheeling", ""]),
	Emoji(char: "🤸‍♂️", names: ["man-cartwheeling", ""]),
	Emoji(char: "🤸", names: ["person-doing-cartwheel"]),
	Emoji(char: "🤹‍♀️", names: ["woman-juggling", ""]),
	Emoji(char: "🤹‍♂️", names: ["man-juggling", ""]),
	Emoji(char: "🤹", names: ["juggling"]),
	Emoji(char: "🤺", names: ["fencer"]),
	Emoji(char: "🤼‍♀️", names: ["woman-wrestling", ""]),
	Emoji(char: "🤼‍♂️", names: ["man-wrestling", ""]),
	Emoji(char: "🤼", names: ["wrestlers"]),
	Emoji(char: "🤽‍♀️", names: ["woman-playing-water-polo", ""]),
	Emoji(char: "🤽‍♂️", names: ["man-playing-water-polo", ""]),
	Emoji(char: "🤽", names: ["water-polo"]),
	Emoji(char: "🤾‍♀️", names: ["woman-playing-handball", ""]),
	Emoji(char: "🤾‍♂️", names: ["man-playing-handball", ""]),
	Emoji(char: "🤾", names: ["handball"]),
	Emoji(char: "🥀", names: ["wilted-flower"]),
	Emoji(char: "🥁", names: ["drum-with-drumsticks"]),
	Emoji(char: "🥂", names: ["clinking-glasses"]),
	Emoji(char: "🥃", names: ["tumbler-glass"]),
	Emoji(char: "🥄", names: ["spoon"]),
	Emoji(char: "🥅", names: ["goal-net"]),
	Emoji(char: "🥇", names: ["first-place-medal"]),
	Emoji(char: "🥈", names: ["second-place-medal"]),
	Emoji(char: "🥉", names: ["third-place-medal"]),
	Emoji(char: "🥊", names: ["boxing-glove"]),
	Emoji(char: "🥋", names: ["martial-arts-uniform"]),
	Emoji(char: "🥌", names: ["curling-stone"]),
	Emoji(char: "🥐", names: ["croissant"]),
	Emoji(char: "🥑", names: ["avocado"]),
	Emoji(char: "🥒", names: ["cucumber"]),
	Emoji(char: "🥓", names: ["bacon"]),
	Emoji(char: "🥔", names: ["potato"]),
	Emoji(char: "🥕", names: ["carrot"]),
	Emoji(char: "🥖", names: ["baguette-bread"]),
	Emoji(char: "🥗", names: ["green-salad"]),
	Emoji(char: "🥘", names: ["shallow-pan-of-food"]),
	Emoji(char: "🥙", names: ["stuffed-flatbread"]),
	Emoji(char: "🥚", names: ["egg"]),
	Emoji(char: "🥛", names: ["glass-of-milk"]),
	Emoji(char: "🥜", names: ["peanuts"]),
	Emoji(char: "🥝", names: ["kiwifruit"]),
	Emoji(char: "🥞", names: ["pancakes"]),
	Emoji(char: "🥟", names: ["dumpling"]),
	Emoji(char: "🥠", names: ["fortune-cookie"]),
	Emoji(char: "🥡", names: ["takeout-box"]),
	Emoji(char: "🥢", names: ["chopsticks"]),
	Emoji(char: "🥣", names: ["bowl-with-spoon"]),
	Emoji(char: "🥤", names: ["cup-with-straw"]),
	Emoji(char: "🥥", names: ["coconut"]),
	Emoji(char: "🥦", names: ["broccoli"]),
	Emoji(char: "🥧", names: ["pie"]),
	Emoji(char: "🥨", names: ["pretzel"]),
	Emoji(char: "🥩", names: ["cut-of-meat"]),
	Emoji(char: "🥪", names: ["sandwich"]),
	Emoji(char: "🥫", names: ["canned-food"]),
	Emoji(char: "🦀", names: ["crab"]),
	Emoji(char: "🦁", names: ["lion-face"]),
	Emoji(char: "🦂", names: ["scorpion"]),
	Emoji(char: "🦃", names: ["turkey"]),
	Emoji(char: "🦄", names: ["unicorn-face"]),
	Emoji(char: "🦅", names: ["eagle"]),
	Emoji(char: "🦆", names: ["duck"]),
	Emoji(char: "🦇", names: ["bat"]),
	Emoji(char: "🦈", names: ["shark"]),
	Emoji(char: "🦉", names: ["owl"]),
	Emoji(char: "🦊", names: ["fox-face"]),
	Emoji(char: "🦋", names: ["butterfly"]),
	Emoji(char: "🦌", names: ["deer"]),
	Emoji(char: "🦍", names: ["gorilla"]),
	Emoji(char: "🦎", names: ["lizard"]),
	Emoji(char: "🦏", names: ["rhinoceros"]),
	Emoji(char: "🦐", names: ["shrimp"]),
	Emoji(char: "🦑", names: ["squid"]),
	Emoji(char: "🦒", names: ["giraffe-face"]),
	Emoji(char: "🦓", names: ["zebra-face"]),
	Emoji(char: "🦔", names: ["hedgehog"]),
	Emoji(char: "🦕", names: ["sauropod"]),
	Emoji(char: "🦖", names: ["t-rex"]),
	Emoji(char: "🦗", names: ["cricket"]),
	Emoji(char: "🧀", names: ["cheese-wedge"]),
	Emoji(char: "🧐", names: ["face-with-monocle"]),
	Emoji(char: "🧑", names: ["adult"]),
	Emoji(char: "🧒", names: ["child"]),
	Emoji(char: "🧓", names: ["older-adult"]),
	Emoji(char: "🧔", names: ["bearded-person"]),
	Emoji(char: "🧕", names: ["person-with-headscarf"]),
	Emoji(char: "🧖‍♀️", names: ["woman-in-steamy-room", ""]),
	Emoji(char: "🧖‍♂️", names: ["man-in-steamy-room", ""]),
	Emoji(char: "🧖", names: ["person-in-steamy-room"]),
	Emoji(char: "🧗‍♀️", names: ["woman-climbing", ""]),
	Emoji(char: "🧗‍♂️", names: ["man-climbing", ""]),
	Emoji(char: "🧗", names: ["person-climbing"]),
	Emoji(char: "🧘‍♀️", names: ["woman-in-lotus-position", ""]),
	Emoji(char: "🧘‍♂️", names: ["man-in-lotus-position", ""]),
	Emoji(char: "🧘", names: ["person-in-lotus-position"]),
	Emoji(char: "🧙‍♀️", names: ["female-mage", ""]),
	Emoji(char: "🧙‍♂️", names: ["male-mage", ""]),
	Emoji(char: "🧙", names: ["mage"]),
	Emoji(char: "🧚‍♀️", names: ["female-fairy", ""]),
	Emoji(char: "🧚‍♂️", names: ["male-fairy", ""]),
	Emoji(char: "🧚", names: ["fairy"]),
	Emoji(char: "🧛‍♀️", names: ["female-vampire", ""]),
	Emoji(char: "🧛‍♂️", names: ["male-vampire", ""]),
	Emoji(char: "🧛", names: ["vampire"]),
	Emoji(char: "🧜‍♀️", names: ["mermaid", ""]),
	Emoji(char: "🧜‍♂️", names: ["merman", ""]),
	Emoji(char: "🧜", names: ["merperson"]),
	Emoji(char: "🧝‍♀️", names: ["female-elf", ""]),
	Emoji(char: "🧝‍♂️", names: ["male-elf", ""]),
	Emoji(char: "🧝", names: ["elf"]),
	Emoji(char: "🧞‍♀️", names: ["female-genie", ""]),
	Emoji(char: "🧞‍♂️", names: ["male-genie", ""]),
	Emoji(char: "🧞", names: ["genie"]),
	Emoji(char: "🧟‍♀️", names: ["female-zombie", ""]),
	Emoji(char: "🧟‍♂️", names: ["male-zombie", ""]),
	Emoji(char: "🧟", names: ["zombie"]),
	Emoji(char: "🧠", names: ["brain"]),
	Emoji(char: "🧡", names: ["orange-heart"]),
	Emoji(char: "🧢", names: ["billed-cap"]),
	Emoji(char: "🧣", names: ["scarf"]),
	Emoji(char: "🧤", names: ["gloves"]),
	Emoji(char: "🧥", names: ["coat"]),
	Emoji(char: "🧦", names: ["socks"]),
	Emoji(char: "‼️", names: ["bangbang", "double-exclamation-mark"]),
	Emoji(char: "⁉️", names: ["interrobang", "exclamation-question-mark"]),
	Emoji(char: "™️", names: ["tm", "trade-mark-sign"]),
	Emoji(char: "ℹ️", names: ["information-source"]),
	Emoji(char: "↔️", names: ["left-right-arrow"]),
	Emoji(char: "↕️", names: ["arrow-up-down", "up-down-arrow"]),
	Emoji(char: "↖️", names: ["arrow-upper-left", "north-west-arrow"]),
	Emoji(char: "↗️", names: ["arrow-upper-right", "north-east-arrow"]),
	Emoji(char: "↘️", names: ["arrow-lower-right", "south-east-arrow"]),
	Emoji(char: "↙️", names: ["arrow-lower-left", "south-west-arrow"]),
	Emoji(char: "↩️", names: ["leftwards-arrow-with-hook"]),
	Emoji(char: "↪️", names: ["arrow-right-hook", "rightwards-arrow-with-hook"]),
	Emoji(char: "⌚", names: ["watch"]),
	Emoji(char: "⌛", names: ["hourglass"]),
	Emoji(char: "⌨️", names: ["keyboard", ""]),
	Emoji(char: "⏏️", names: ["eject", ""]),
	Emoji(char: "⏩", names: ["fast-forward", "black-right-pointing-double-triangle"]),
	Emoji(char: "⏪", names: ["rewind", "black-left-pointing-double-triangle"]),
	Emoji(char: "⏫", names: ["arrow-double-up", "black-up-pointing-double-triangle"]),
	Emoji(char: "⏬", names: ["arrow-double-down", "black-down-pointing-double-triangle"]),
	Emoji(char: "⏭️", names: ["black-right-pointing-double-triangle-with-vertical-bar", ""]),
	Emoji(char: "⏮️", names: ["black-left-pointing-double-triangle-with-vertical-bar", ""]),
	Emoji(char: "⏯️", names: ["black-right-pointing-triangle-with-double-vertical-bar", ""]),
	Emoji(char: "⏰", names: ["alarm-clock"]),
	Emoji(char: "⏱️", names: ["stopwatch", ""]),
	Emoji(char: "⏲️", names: ["timer-clock", ""]),
	Emoji(char: "⏳", names: ["hourglass-flowing-sand", "hourglass-with-flowing-sand"]),
	Emoji(char: "⏸️", names: ["double-vertical-bar", ""]),
	Emoji(char: "⏹️", names: ["black-square-for-stop", ""]),
	Emoji(char: "⏺️", names: ["black-circle-for-record", ""]),
	Emoji(char: "Ⓜ️", names: ["m", "circled-latin-capital-letter-m"]),
	Emoji(char: "▪️", names: ["black-small-square"]),
	Emoji(char: "▫️", names: ["white-small-square"]),
	Emoji(char: "▶️", names: ["arrow-forward", "black-right-pointing-triangle"]),
	Emoji(char: "◀️", names: ["arrow-backward", "black-left-pointing-triangle"]),
	Emoji(char: "◻️", names: ["white-medium-square"]),
	Emoji(char: "◼️", names: ["black-medium-square"]),
	Emoji(char: "◽", names: ["white-medium-small-square"]),
	Emoji(char: "◾", names: ["black-medium-small-square"]),
	Emoji(char: "☀️", names: ["sunny", "black-sun-with-rays"]),
	Emoji(char: "☁️", names: ["cloud"]),
	Emoji(char: "☂️", names: ["umbrella", ""]),
	Emoji(char: "☃️", names: ["snowman", ""]),
	Emoji(char: "☄️", names: ["comet", ""]),
	Emoji(char: "☎️", names: ["phone", "black-telephone"]),
	Emoji(char: "☑️", names: ["ballot-box-with-check"]),
	Emoji(char: "☔", names: ["umbrella-with-rain-drops"]),
	Emoji(char: "☕", names: ["coffee", "hot-beverage"]),
	Emoji(char: "☘️", names: ["shamrock", ""]),
	Emoji(char: "☝️", names: ["point-up", "white-up-pointing-index"]),
	Emoji(char: "☠️", names: ["skull-and-crossbones", ""]),
	Emoji(char: "☢️", names: ["radioactive-sign", ""]),
	Emoji(char: "☣️", names: ["biohazard-sign", ""]),
	Emoji(char: "☦️", names: ["orthodox-cross", ""]),
	Emoji(char: "☪️", names: ["star-and-crescent", ""]),
	Emoji(char: "☮️", names: ["peace-symbol", ""]),
	Emoji(char: "☯️", names: ["yin-yang", ""]),
	Emoji(char: "☸️", names: ["wheel-of-dharma", ""]),
	Emoji(char: "☹️", names: ["white-frowning-face", ""]),
	Emoji(char: "☺️", names: ["relaxed", "white-smiling-face"]),
	Emoji(char: "♀️", names: ["female-sign", ""]),
	Emoji(char: "♂️", names: ["male-sign", ""]),
	Emoji(char: "♈", names: ["aries"]),
	Emoji(char: "♉", names: ["taurus"]),
	Emoji(char: "♊", names: ["gemini"]),
	Emoji(char: "♋", names: ["cancer"]),
	Emoji(char: "♌", names: ["leo"]),
	Emoji(char: "♍", names: ["virgo"]),
	Emoji(char: "♎", names: ["libra"]),
	Emoji(char: "♏", names: ["scorpius"]),
	Emoji(char: "♐", names: ["sagittarius"]),
	Emoji(char: "♑", names: ["capricorn"]),
	Emoji(char: "♒", names: ["aquarius"]),
	Emoji(char: "♓", names: ["pisces"]),
	Emoji(char: "♠️", names: ["spades", "black-spade-suit"]),
	Emoji(char: "♣️", names: ["clubs", "black-club-suit"]),
	Emoji(char: "♥️", names: ["hearts", "black-heart-suit"]),
	Emoji(char: "♦️", names: ["diamonds", "black-diamond-suit"]),
	Emoji(char: "♨️", names: ["hotsprings", "hot-springs"]),
	Emoji(char: "♻️", names: ["recycle", "black-universal-recycling-symbol"]),
	Emoji(char: "♿", names: ["wheelchair", "wheelchair-symbol"]),
	Emoji(char: "⚒️", names: ["hammer-and-pick", ""]),
	Emoji(char: "⚓", names: ["anchor"]),
	Emoji(char: "⚔️", names: ["crossed-swords", ""]),
	Emoji(char: "⚕️", names: ["staff-of-aesculapius", ""]),
	Emoji(char: "⚖️", names: ["scales", ""]),
	Emoji(char: "⚗️", names: ["alembic", ""]),
	Emoji(char: "⚙️", names: ["gear", ""]),
	Emoji(char: "⚛️", names: ["atom-symbol", ""]),
	Emoji(char: "⚜️", names: ["fleur-de-lis", ""]),
	Emoji(char: "⚠️", names: ["warning", "warning-sign"]),
	Emoji(char: "⚡", names: ["zap", "high-voltage-sign"]),
	Emoji(char: "⚪", names: ["white-circle", "medium-white-circle"]),
	Emoji(char: "⚫", names: ["black-circle", "medium-black-circle"]),
	Emoji(char: "⚰️", names: ["coffin", ""]),
	Emoji(char: "⚱️", names: ["funeral-urn", ""]),
	Emoji(char: "⚽", names: ["soccer", "soccer-ball"]),
	Emoji(char: "⚾", names: ["baseball"]),
	Emoji(char: "⛄", names: ["snowman-without-snow"]),
	Emoji(char: "⛅", names: ["partly-sunny", "sun-behind-cloud"]),
	Emoji(char: "⛈️", names: ["thunder-cloud-and-rain", ""]),
	Emoji(char: "⛎", names: ["ophiuchus"]),
	Emoji(char: "⛏️", names: ["pick", ""]),
	Emoji(char: "⛑️", names: ["helmet-with-white-cross", ""]),
	Emoji(char: "⛓️", names: ["chains", ""]),
	Emoji(char: "⛔", names: ["no-entry"]),
	Emoji(char: "⛩️", names: ["shinto-shrine", ""]),
	Emoji(char: "⛪", names: ["church"]),
	Emoji(char: "⛰️", names: ["mountain", ""]),
	Emoji(char: "⛱️", names: ["umbrella-on-ground", ""]),
	Emoji(char: "⛲", names: ["fountain"]),
	Emoji(char: "⛳", names: ["golf", "flag-in-hole"]),
	Emoji(char: "⛴️", names: ["ferry", ""]),
	Emoji(char: "⛵", names: ["boat", "sailboat"]),
	Emoji(char: "⛷️", names: ["skier", ""]),
	Emoji(char: "⛸️", names: ["ice-skate", ""]),
	Emoji(char: "⛹️‍♀️", names: ["woman-bouncing-ball", ""]),
	Emoji(char: "⛹️‍♂️", names: ["man-bouncing-ball", ""]),
	Emoji(char: "⛹️", names: ["person-with-ball", ""]),
	Emoji(char: "⛺", names: ["tent"]),
	Emoji(char: "⛽", names: ["fuelpump", "fuel-pump"]),
	Emoji(char: "✂️", names: ["scissors", "black-scissors"]),
	Emoji(char: "✅", names: ["white-check-mark", "white-heavy-check-mark"]),
	Emoji(char: "✈️", names: ["airplane"]),
	Emoji(char: "✉️", names: ["email", "envelope"]),
	Emoji(char: "✊", names: ["fist", "raised-fist"]),
	Emoji(char: "✋", names: ["hand", "raised-hand"]),
	Emoji(char: "✌️", names: ["v", "victory-hand"]),
	Emoji(char: "✍️", names: ["writing-hand", ""]),
	Emoji(char: "✏️", names: ["pencil2", "pencil"]),
	Emoji(char: "✒️", names: ["black-nib"]),
	Emoji(char: "✔️", names: ["heavy-check-mark"]),
	Emoji(char: "✖️", names: ["heavy-multiplication-x"]),
	Emoji(char: "✝️", names: ["latin-cross", ""]),
	Emoji(char: "✡️", names: ["star-of-david", ""]),
	Emoji(char: "✨", names: ["sparkles"]),
	Emoji(char: "✳️", names: ["eight-spoked-asterisk"]),
	Emoji(char: "✴️", names: ["eight-pointed-black-star"]),
	Emoji(char: "❄️", names: ["snowflake"]),
	Emoji(char: "❇️", names: ["sparkle"]),
	Emoji(char: "❌", names: ["x", "cross-mark"]),
	Emoji(char: "❎", names: ["negative-squared-cross-mark"]),
	Emoji(char: "❓", names: ["question", "black-question-mark-ornament"]),
	Emoji(char: "❔", names: ["grey-question", "white-question-mark-ornament"]),
	Emoji(char: "❕", names: ["grey-exclamation", "white-exclamation-mark-ornament"]),
	Emoji(char: "❗", names: ["exclamation", "heavy-exclamation-mark-symbol"]),
	Emoji(char: "❣️", names: ["heavy-heart-exclamation-mark-ornament", ""]),
	Emoji(char: "❤️", names: ["heart", "heavy-black-heart"]),
	Emoji(char: "➕", names: ["heavy-plus-sign"]),
	Emoji(char: "➖", names: ["heavy-minus-sign"]),
	Emoji(char: "➗", names: ["heavy-division-sign"]),
	Emoji(char: "➡️", names: ["arrow-right", "black-rightwards-arrow"]),
	Emoji(char: "➰", names: ["curly-loop"]),
	Emoji(char: "➿", names: ["loop", "double-curly-loop"]),
	Emoji(char: "⤴️", names: ["arrow-heading-up", "arrow-pointing-rightwards-then-curving-upwards"]),
	Emoji(char: "⤵️", names: ["arrow-heading-down", "arrow-pointing-rightwards-then-curving-downwards"]),
	Emoji(char: "⬅️", names: ["arrow-left", "leftwards-black-arrow"]),
	Emoji(char: "⬆️", names: ["arrow-up", "upwards-black-arrow"]),
	Emoji(char: "⬇️", names: ["arrow-down", "downwards-black-arrow"]),
	Emoji(char: "⬛", names: ["black-large-square"]),
	Emoji(char: "⬜", names: ["white-large-square"]),
	Emoji(char: "⭐", names: ["star", "white-medium-star"]),
	Emoji(char: "⭕", names: ["o", "heavy-large-circle"]),
	Emoji(char: "〰️", names: ["wavy-dash"]),
	Emoji(char: "〽️", names: ["part-alternation-mark"]),
	Emoji(char: "㊗️", names: ["congratulations", "circled-ideograph-congratulation"]),
	Emoji(char: "㊙️", names: ["secret", "circled-ideograph-secret"]),
]